// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.33.5
// source: enum.proto

/* eslint-disable */

export const protobufPackage = "protobuf";

export enum CrossType {
  PAI_MAI_HANG = 0,
  BATTLE = 1,
  UNRECOGNIZED = -1,
}

export function crossTypeFromJSON(object: any): CrossType {
  switch (object) {
    case 0:
    case "PAI_MAI_HANG":
      return CrossType.PAI_MAI_HANG;
    case 1:
    case "BATTLE":
      return CrossType.BATTLE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CrossType.UNRECOGNIZED;
  }
}

export function crossTypeToJSON(object: CrossType): string {
  switch (object) {
    case CrossType.PAI_MAI_HANG:
      return "PAI_MAI_HANG";
    case CrossType.BATTLE:
      return "BATTLE";
    case CrossType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum BattleSide {
  /** watch - 观战 */
  watch = 0,
  /** attack - 进攻 */
  attack = 1,
  /** defend - 防守 */
  defend = 2,
  UNRECOGNIZED = -1,
}

export function battleSideFromJSON(object: any): BattleSide {
  switch (object) {
    case 0:
    case "watch":
      return BattleSide.watch;
    case 1:
    case "attack":
      return BattleSide.attack;
    case 2:
    case "defend":
      return BattleSide.defend;
    case -1:
    case "UNRECOGNIZED":
    default:
      return BattleSide.UNRECOGNIZED;
  }
}

export function battleSideToJSON(object: BattleSide): string {
  switch (object) {
    case BattleSide.watch:
      return "watch";
    case BattleSide.attack:
      return "attack";
    case BattleSide.defend:
      return "defend";
    case BattleSide.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
