// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.33.5
// source: enum.proto

/* eslint-disable */

export const protobufPackage = "protobuf";

export enum CrossType {
  PAI_MAI_HANG = 0,
  BATTLE = 1,
  UNRECOGNIZED = -1,
}

export function crossTypeFromJSON(object: any): CrossType {
  switch (object) {
    case 0:
    case "PAI_MAI_HANG":
      return CrossType.PAI_MAI_HANG;
    case 1:
    case "BATTLE":
      return CrossType.BATTLE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CrossType.UNRECOGNIZED;
  }
}

export function crossTypeToJSON(object: CrossType): string {
  switch (object) {
    case CrossType.PAI_MAI_HANG:
      return "PAI_MAI_HANG";
    case CrossType.BATTLE:
      return "BATTLE";
    case CrossType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
