// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.33.5
// source: MessageCity.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { BattleSide, battleSideFromJSON, battleSideToJSON } from "./enum";
import { CityBattleDetail, CityInfo } from "./structure";

export const protobufPackage = "protobuf";

/**
 * 获取城池列表
 * @Id(1501)
 */
export interface CsGetCityList {
}

/**
 * 获取城池列表
 * @Id(1502)
 */
export interface ScGetCityList {
  cityInfos: CityInfo[];
}

/**
 * 获取城池详情
 * @Id(1503)
 */
export interface CsGetCityDetail {
  cityId: number;
}

/**
 * 获取城池详情
 * @Id(1504)
 */
export interface ScGetCityDetail {
  cityInfo?: CityInfo | undefined;
}

/**
 * 获取玩家城池的详情
 * @Id(1505)
 */
export interface CsPlayerCityInfo {
}

/**
 * 获取玩家城池的详情
 * @Id(1506)
 */
export interface ScPlayerCityInfo {
  /** 当前已经解锁的最大城池id */
  unlockedCityMaxId: number;
  /** 下一个城池需要的已经通关的副本 */
  nextUnlockInstanceIds: number[];
}

/**
 * 城战详细信息
 * @Id(1507)
 */
export interface CsCityBattleDetail {
  cityId: number;
}

/**
 * 城战详细信息
 * @Id(1508)
 */
export interface ScCityBattleDetail {
  detail?: CityBattleDetail | undefined;
}

/**
 * 都城宣战
 * @Id(1509)
 */
export interface CsDeclareCapital {
  cityId: number;
}

/**
 * 都城宣战
 * @Id(1510)
 */
export interface ScDeclareCapital {
}

/**
 * 派遣部队
 * @Id(1511)
 */
export interface CsDispatchTroops {
  cityId: number;
  /** 1-进攻 2-防御 */
  side: number;
  heroIds: number[];
}

/**
 * 派遣部队
 * @Id(1512)
 */
export interface ScDispatchTroops {
}

/**
 * 撤回防守部队
 * @Id(1513)
 */
export interface CsWithdrawDefendingTroops {
  cityId: number;
  dispatchId: string;
}

/**
 * 撤回防守部队
 * @Id(1514)
 */
export interface ScWithdrawDefendingTroops {
}

/**
 * 治疗重伤武将
 * @Id(1515)
 */
export interface CsHealInjuredHeroes {
  cityId: number;
  heroIds: number[];
}

/**
 * 治疗重伤武将
 * @Id(1516)
 */
export interface ScHealInjuredHeroes {
}

/**
 * 阵亡武将的信息
 * @Id(1517)
 */
export interface CsHeroDeadList {
  cityId: number;
}

/**
 * 阵亡武将的信息
 * @Id(1518)
 */
export interface ScHeroDeadList {
  deadInfo: HeroDeadInfo[];
}

export interface HeroDeadInfo {
  heroTableId: number;
  healTimes: number;
}

/**
 * 城池战斗的结果
 * @Id(1519)
 */
export interface ScCityBattleResult {
  cityInfo?:
    | CityInfo
    | undefined;
  /** 胜利方 1-进攻胜利 2-防守胜利 */
  winnerSize: number;
  battleSide: BattleSide;
}

function createBaseCsGetCityList(): CsGetCityList {
  return {};
}

export const CsGetCityList: MessageFns<CsGetCityList> = {
  encode(_: CsGetCityList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsGetCityList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsGetCityList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CsGetCityList {
    return {};
  },

  toJSON(_: CsGetCityList): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CsGetCityList>, I>>(base?: I): CsGetCityList {
    return CsGetCityList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsGetCityList>, I>>(_: I): CsGetCityList {
    const message = createBaseCsGetCityList();
    return message;
  },
};

function createBaseScGetCityList(): ScGetCityList {
  return { cityInfos: [] };
}

export const ScGetCityList: MessageFns<ScGetCityList> = {
  encode(message: ScGetCityList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.cityInfos) {
      CityInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScGetCityList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScGetCityList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cityInfos.push(CityInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScGetCityList {
    return {
      cityInfos: globalThis.Array.isArray(object?.cityInfos)
        ? object.cityInfos.map((e: any) => CityInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ScGetCityList): unknown {
    const obj: any = {};
    if (message.cityInfos?.length) {
      obj.cityInfos = message.cityInfos.map((e) => CityInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScGetCityList>, I>>(base?: I): ScGetCityList {
    return ScGetCityList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScGetCityList>, I>>(object: I): ScGetCityList {
    const message = createBaseScGetCityList();
    message.cityInfos = object.cityInfos?.map((e) => CityInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCsGetCityDetail(): CsGetCityDetail {
  return { cityId: 0 };
}

export const CsGetCityDetail: MessageFns<CsGetCityDetail> = {
  encode(message: CsGetCityDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cityId !== 0) {
      writer.uint32(8).int32(message.cityId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsGetCityDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsGetCityDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.cityId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsGetCityDetail {
    return { cityId: isSet(object.cityId) ? globalThis.Number(object.cityId) : 0 };
  },

  toJSON(message: CsGetCityDetail): unknown {
    const obj: any = {};
    if (message.cityId !== 0) {
      obj.cityId = Math.round(message.cityId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsGetCityDetail>, I>>(base?: I): CsGetCityDetail {
    return CsGetCityDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsGetCityDetail>, I>>(object: I): CsGetCityDetail {
    const message = createBaseCsGetCityDetail();
    message.cityId = object.cityId ?? 0;
    return message;
  },
};

function createBaseScGetCityDetail(): ScGetCityDetail {
  return { cityInfo: undefined };
}

export const ScGetCityDetail: MessageFns<ScGetCityDetail> = {
  encode(message: ScGetCityDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cityInfo !== undefined) {
      CityInfo.encode(message.cityInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScGetCityDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScGetCityDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cityInfo = CityInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScGetCityDetail {
    return { cityInfo: isSet(object.cityInfo) ? CityInfo.fromJSON(object.cityInfo) : undefined };
  },

  toJSON(message: ScGetCityDetail): unknown {
    const obj: any = {};
    if (message.cityInfo !== undefined) {
      obj.cityInfo = CityInfo.toJSON(message.cityInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScGetCityDetail>, I>>(base?: I): ScGetCityDetail {
    return ScGetCityDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScGetCityDetail>, I>>(object: I): ScGetCityDetail {
    const message = createBaseScGetCityDetail();
    message.cityInfo = (object.cityInfo !== undefined && object.cityInfo !== null)
      ? CityInfo.fromPartial(object.cityInfo)
      : undefined;
    return message;
  },
};

function createBaseCsPlayerCityInfo(): CsPlayerCityInfo {
  return {};
}

export const CsPlayerCityInfo: MessageFns<CsPlayerCityInfo> = {
  encode(_: CsPlayerCityInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsPlayerCityInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsPlayerCityInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CsPlayerCityInfo {
    return {};
  },

  toJSON(_: CsPlayerCityInfo): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CsPlayerCityInfo>, I>>(base?: I): CsPlayerCityInfo {
    return CsPlayerCityInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsPlayerCityInfo>, I>>(_: I): CsPlayerCityInfo {
    const message = createBaseCsPlayerCityInfo();
    return message;
  },
};

function createBaseScPlayerCityInfo(): ScPlayerCityInfo {
  return { unlockedCityMaxId: 0, nextUnlockInstanceIds: [] };
}

export const ScPlayerCityInfo: MessageFns<ScPlayerCityInfo> = {
  encode(message: ScPlayerCityInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.unlockedCityMaxId !== 0) {
      writer.uint32(8).int32(message.unlockedCityMaxId);
    }
    writer.uint32(18).fork();
    for (const v of message.nextUnlockInstanceIds) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScPlayerCityInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScPlayerCityInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.unlockedCityMaxId = reader.int32();
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.nextUnlockInstanceIds.push(reader.int32());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.nextUnlockInstanceIds.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScPlayerCityInfo {
    return {
      unlockedCityMaxId: isSet(object.unlockedCityMaxId) ? globalThis.Number(object.unlockedCityMaxId) : 0,
      nextUnlockInstanceIds: globalThis.Array.isArray(object?.nextUnlockInstanceIds)
        ? object.nextUnlockInstanceIds.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: ScPlayerCityInfo): unknown {
    const obj: any = {};
    if (message.unlockedCityMaxId !== 0) {
      obj.unlockedCityMaxId = Math.round(message.unlockedCityMaxId);
    }
    if (message.nextUnlockInstanceIds?.length) {
      obj.nextUnlockInstanceIds = message.nextUnlockInstanceIds.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScPlayerCityInfo>, I>>(base?: I): ScPlayerCityInfo {
    return ScPlayerCityInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScPlayerCityInfo>, I>>(object: I): ScPlayerCityInfo {
    const message = createBaseScPlayerCityInfo();
    message.unlockedCityMaxId = object.unlockedCityMaxId ?? 0;
    message.nextUnlockInstanceIds = object.nextUnlockInstanceIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseCsCityBattleDetail(): CsCityBattleDetail {
  return { cityId: 0 };
}

export const CsCityBattleDetail: MessageFns<CsCityBattleDetail> = {
  encode(message: CsCityBattleDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cityId !== 0) {
      writer.uint32(8).int32(message.cityId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsCityBattleDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsCityBattleDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.cityId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsCityBattleDetail {
    return { cityId: isSet(object.cityId) ? globalThis.Number(object.cityId) : 0 };
  },

  toJSON(message: CsCityBattleDetail): unknown {
    const obj: any = {};
    if (message.cityId !== 0) {
      obj.cityId = Math.round(message.cityId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsCityBattleDetail>, I>>(base?: I): CsCityBattleDetail {
    return CsCityBattleDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsCityBattleDetail>, I>>(object: I): CsCityBattleDetail {
    const message = createBaseCsCityBattleDetail();
    message.cityId = object.cityId ?? 0;
    return message;
  },
};

function createBaseScCityBattleDetail(): ScCityBattleDetail {
  return { detail: undefined };
}

export const ScCityBattleDetail: MessageFns<ScCityBattleDetail> = {
  encode(message: ScCityBattleDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.detail !== undefined) {
      CityBattleDetail.encode(message.detail, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScCityBattleDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScCityBattleDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.detail = CityBattleDetail.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScCityBattleDetail {
    return { detail: isSet(object.detail) ? CityBattleDetail.fromJSON(object.detail) : undefined };
  },

  toJSON(message: ScCityBattleDetail): unknown {
    const obj: any = {};
    if (message.detail !== undefined) {
      obj.detail = CityBattleDetail.toJSON(message.detail);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScCityBattleDetail>, I>>(base?: I): ScCityBattleDetail {
    return ScCityBattleDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScCityBattleDetail>, I>>(object: I): ScCityBattleDetail {
    const message = createBaseScCityBattleDetail();
    message.detail = (object.detail !== undefined && object.detail !== null)
      ? CityBattleDetail.fromPartial(object.detail)
      : undefined;
    return message;
  },
};

function createBaseCsDeclareCapital(): CsDeclareCapital {
  return { cityId: 0 };
}

export const CsDeclareCapital: MessageFns<CsDeclareCapital> = {
  encode(message: CsDeclareCapital, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cityId !== 0) {
      writer.uint32(8).int32(message.cityId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsDeclareCapital {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsDeclareCapital();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.cityId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsDeclareCapital {
    return { cityId: isSet(object.cityId) ? globalThis.Number(object.cityId) : 0 };
  },

  toJSON(message: CsDeclareCapital): unknown {
    const obj: any = {};
    if (message.cityId !== 0) {
      obj.cityId = Math.round(message.cityId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsDeclareCapital>, I>>(base?: I): CsDeclareCapital {
    return CsDeclareCapital.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsDeclareCapital>, I>>(object: I): CsDeclareCapital {
    const message = createBaseCsDeclareCapital();
    message.cityId = object.cityId ?? 0;
    return message;
  },
};

function createBaseScDeclareCapital(): ScDeclareCapital {
  return {};
}

export const ScDeclareCapital: MessageFns<ScDeclareCapital> = {
  encode(_: ScDeclareCapital, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScDeclareCapital {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScDeclareCapital();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ScDeclareCapital {
    return {};
  },

  toJSON(_: ScDeclareCapital): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ScDeclareCapital>, I>>(base?: I): ScDeclareCapital {
    return ScDeclareCapital.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScDeclareCapital>, I>>(_: I): ScDeclareCapital {
    const message = createBaseScDeclareCapital();
    return message;
  },
};

function createBaseCsDispatchTroops(): CsDispatchTroops {
  return { cityId: 0, side: 0, heroIds: [] };
}

export const CsDispatchTroops: MessageFns<CsDispatchTroops> = {
  encode(message: CsDispatchTroops, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cityId !== 0) {
      writer.uint32(8).int32(message.cityId);
    }
    if (message.side !== 0) {
      writer.uint32(16).int32(message.side);
    }
    writer.uint32(26).fork();
    for (const v of message.heroIds) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsDispatchTroops {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsDispatchTroops();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.cityId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.side = reader.int32();
          continue;
        }
        case 3: {
          if (tag === 24) {
            message.heroIds.push(reader.int32());

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.heroIds.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsDispatchTroops {
    return {
      cityId: isSet(object.cityId) ? globalThis.Number(object.cityId) : 0,
      side: isSet(object.side) ? globalThis.Number(object.side) : 0,
      heroIds: globalThis.Array.isArray(object?.heroIds) ? object.heroIds.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: CsDispatchTroops): unknown {
    const obj: any = {};
    if (message.cityId !== 0) {
      obj.cityId = Math.round(message.cityId);
    }
    if (message.side !== 0) {
      obj.side = Math.round(message.side);
    }
    if (message.heroIds?.length) {
      obj.heroIds = message.heroIds.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsDispatchTroops>, I>>(base?: I): CsDispatchTroops {
    return CsDispatchTroops.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsDispatchTroops>, I>>(object: I): CsDispatchTroops {
    const message = createBaseCsDispatchTroops();
    message.cityId = object.cityId ?? 0;
    message.side = object.side ?? 0;
    message.heroIds = object.heroIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseScDispatchTroops(): ScDispatchTroops {
  return {};
}

export const ScDispatchTroops: MessageFns<ScDispatchTroops> = {
  encode(_: ScDispatchTroops, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScDispatchTroops {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScDispatchTroops();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ScDispatchTroops {
    return {};
  },

  toJSON(_: ScDispatchTroops): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ScDispatchTroops>, I>>(base?: I): ScDispatchTroops {
    return ScDispatchTroops.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScDispatchTroops>, I>>(_: I): ScDispatchTroops {
    const message = createBaseScDispatchTroops();
    return message;
  },
};

function createBaseCsWithdrawDefendingTroops(): CsWithdrawDefendingTroops {
  return { cityId: 0, dispatchId: "" };
}

export const CsWithdrawDefendingTroops: MessageFns<CsWithdrawDefendingTroops> = {
  encode(message: CsWithdrawDefendingTroops, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cityId !== 0) {
      writer.uint32(8).int32(message.cityId);
    }
    if (message.dispatchId !== "") {
      writer.uint32(18).string(message.dispatchId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsWithdrawDefendingTroops {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsWithdrawDefendingTroops();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.cityId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.dispatchId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsWithdrawDefendingTroops {
    return {
      cityId: isSet(object.cityId) ? globalThis.Number(object.cityId) : 0,
      dispatchId: isSet(object.dispatchId) ? globalThis.String(object.dispatchId) : "",
    };
  },

  toJSON(message: CsWithdrawDefendingTroops): unknown {
    const obj: any = {};
    if (message.cityId !== 0) {
      obj.cityId = Math.round(message.cityId);
    }
    if (message.dispatchId !== "") {
      obj.dispatchId = message.dispatchId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsWithdrawDefendingTroops>, I>>(base?: I): CsWithdrawDefendingTroops {
    return CsWithdrawDefendingTroops.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsWithdrawDefendingTroops>, I>>(object: I): CsWithdrawDefendingTroops {
    const message = createBaseCsWithdrawDefendingTroops();
    message.cityId = object.cityId ?? 0;
    message.dispatchId = object.dispatchId ?? "";
    return message;
  },
};

function createBaseScWithdrawDefendingTroops(): ScWithdrawDefendingTroops {
  return {};
}

export const ScWithdrawDefendingTroops: MessageFns<ScWithdrawDefendingTroops> = {
  encode(_: ScWithdrawDefendingTroops, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScWithdrawDefendingTroops {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScWithdrawDefendingTroops();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ScWithdrawDefendingTroops {
    return {};
  },

  toJSON(_: ScWithdrawDefendingTroops): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ScWithdrawDefendingTroops>, I>>(base?: I): ScWithdrawDefendingTroops {
    return ScWithdrawDefendingTroops.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScWithdrawDefendingTroops>, I>>(_: I): ScWithdrawDefendingTroops {
    const message = createBaseScWithdrawDefendingTroops();
    return message;
  },
};

function createBaseCsHealInjuredHeroes(): CsHealInjuredHeroes {
  return { cityId: 0, heroIds: [] };
}

export const CsHealInjuredHeroes: MessageFns<CsHealInjuredHeroes> = {
  encode(message: CsHealInjuredHeroes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cityId !== 0) {
      writer.uint32(8).int32(message.cityId);
    }
    writer.uint32(18).fork();
    for (const v of message.heroIds) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsHealInjuredHeroes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsHealInjuredHeroes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.cityId = reader.int32();
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.heroIds.push(reader.int32());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.heroIds.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsHealInjuredHeroes {
    return {
      cityId: isSet(object.cityId) ? globalThis.Number(object.cityId) : 0,
      heroIds: globalThis.Array.isArray(object?.heroIds) ? object.heroIds.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: CsHealInjuredHeroes): unknown {
    const obj: any = {};
    if (message.cityId !== 0) {
      obj.cityId = Math.round(message.cityId);
    }
    if (message.heroIds?.length) {
      obj.heroIds = message.heroIds.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsHealInjuredHeroes>, I>>(base?: I): CsHealInjuredHeroes {
    return CsHealInjuredHeroes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsHealInjuredHeroes>, I>>(object: I): CsHealInjuredHeroes {
    const message = createBaseCsHealInjuredHeroes();
    message.cityId = object.cityId ?? 0;
    message.heroIds = object.heroIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseScHealInjuredHeroes(): ScHealInjuredHeroes {
  return {};
}

export const ScHealInjuredHeroes: MessageFns<ScHealInjuredHeroes> = {
  encode(_: ScHealInjuredHeroes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScHealInjuredHeroes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScHealInjuredHeroes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ScHealInjuredHeroes {
    return {};
  },

  toJSON(_: ScHealInjuredHeroes): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ScHealInjuredHeroes>, I>>(base?: I): ScHealInjuredHeroes {
    return ScHealInjuredHeroes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScHealInjuredHeroes>, I>>(_: I): ScHealInjuredHeroes {
    const message = createBaseScHealInjuredHeroes();
    return message;
  },
};

function createBaseCsHeroDeadList(): CsHeroDeadList {
  return { cityId: 0 };
}

export const CsHeroDeadList: MessageFns<CsHeroDeadList> = {
  encode(message: CsHeroDeadList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cityId !== 0) {
      writer.uint32(8).int32(message.cityId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsHeroDeadList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsHeroDeadList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.cityId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsHeroDeadList {
    return { cityId: isSet(object.cityId) ? globalThis.Number(object.cityId) : 0 };
  },

  toJSON(message: CsHeroDeadList): unknown {
    const obj: any = {};
    if (message.cityId !== 0) {
      obj.cityId = Math.round(message.cityId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsHeroDeadList>, I>>(base?: I): CsHeroDeadList {
    return CsHeroDeadList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsHeroDeadList>, I>>(object: I): CsHeroDeadList {
    const message = createBaseCsHeroDeadList();
    message.cityId = object.cityId ?? 0;
    return message;
  },
};

function createBaseScHeroDeadList(): ScHeroDeadList {
  return { deadInfo: [] };
}

export const ScHeroDeadList: MessageFns<ScHeroDeadList> = {
  encode(message: ScHeroDeadList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.deadInfo) {
      HeroDeadInfo.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScHeroDeadList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScHeroDeadList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.deadInfo.push(HeroDeadInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScHeroDeadList {
    return {
      deadInfo: globalThis.Array.isArray(object?.deadInfo)
        ? object.deadInfo.map((e: any) => HeroDeadInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ScHeroDeadList): unknown {
    const obj: any = {};
    if (message.deadInfo?.length) {
      obj.deadInfo = message.deadInfo.map((e) => HeroDeadInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScHeroDeadList>, I>>(base?: I): ScHeroDeadList {
    return ScHeroDeadList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScHeroDeadList>, I>>(object: I): ScHeroDeadList {
    const message = createBaseScHeroDeadList();
    message.deadInfo = object.deadInfo?.map((e) => HeroDeadInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseHeroDeadInfo(): HeroDeadInfo {
  return { heroTableId: 0, healTimes: 0 };
}

export const HeroDeadInfo: MessageFns<HeroDeadInfo> = {
  encode(message: HeroDeadInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.heroTableId !== 0) {
      writer.uint32(8).int32(message.heroTableId);
    }
    if (message.healTimes !== 0) {
      writer.uint32(16).int32(message.healTimes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HeroDeadInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeroDeadInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.heroTableId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.healTimes = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HeroDeadInfo {
    return {
      heroTableId: isSet(object.heroTableId) ? globalThis.Number(object.heroTableId) : 0,
      healTimes: isSet(object.healTimes) ? globalThis.Number(object.healTimes) : 0,
    };
  },

  toJSON(message: HeroDeadInfo): unknown {
    const obj: any = {};
    if (message.heroTableId !== 0) {
      obj.heroTableId = Math.round(message.heroTableId);
    }
    if (message.healTimes !== 0) {
      obj.healTimes = Math.round(message.healTimes);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HeroDeadInfo>, I>>(base?: I): HeroDeadInfo {
    return HeroDeadInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HeroDeadInfo>, I>>(object: I): HeroDeadInfo {
    const message = createBaseHeroDeadInfo();
    message.heroTableId = object.heroTableId ?? 0;
    message.healTimes = object.healTimes ?? 0;
    return message;
  },
};

function createBaseScCityBattleResult(): ScCityBattleResult {
  return { cityInfo: undefined, winnerSize: 0, battleSide: 0 };
}

export const ScCityBattleResult: MessageFns<ScCityBattleResult> = {
  encode(message: ScCityBattleResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cityInfo !== undefined) {
      CityInfo.encode(message.cityInfo, writer.uint32(10).fork()).join();
    }
    if (message.winnerSize !== 0) {
      writer.uint32(16).int32(message.winnerSize);
    }
    if (message.battleSide !== 0) {
      writer.uint32(24).int32(message.battleSide);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScCityBattleResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScCityBattleResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cityInfo = CityInfo.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.winnerSize = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.battleSide = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScCityBattleResult {
    return {
      cityInfo: isSet(object.cityInfo) ? CityInfo.fromJSON(object.cityInfo) : undefined,
      winnerSize: isSet(object.winnerSize) ? globalThis.Number(object.winnerSize) : 0,
      battleSide: isSet(object.battleSide) ? battleSideFromJSON(object.battleSide) : 0,
    };
  },

  toJSON(message: ScCityBattleResult): unknown {
    const obj: any = {};
    if (message.cityInfo !== undefined) {
      obj.cityInfo = CityInfo.toJSON(message.cityInfo);
    }
    if (message.winnerSize !== 0) {
      obj.winnerSize = Math.round(message.winnerSize);
    }
    if (message.battleSide !== 0) {
      obj.battleSide = battleSideToJSON(message.battleSide);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScCityBattleResult>, I>>(base?: I): ScCityBattleResult {
    return ScCityBattleResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScCityBattleResult>, I>>(object: I): ScCityBattleResult {
    const message = createBaseScCityBattleResult();
    message.cityInfo = (object.cityInfo !== undefined && object.cityInfo !== null)
      ? CityInfo.fromPartial(object.cityInfo)
      : undefined;
    message.winnerSize = object.winnerSize ?? 0;
    message.battleSide = object.battleSide ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}

export const csGetCityListId: number = 1501;
export const scGetCityListId: number = 1502;
export const csGetCityDetailId: number = 1503;
export const scGetCityDetailId: number = 1504;
export const csPlayerCityInfoId: number = 1505;
export const scPlayerCityInfoId: number = 1506;
export const csCityBattleDetailId: number = 1507;
export const scCityBattleDetailId: number = 1508;
export const csDeclareCapitalId: number = 1509;
export const scDeclareCapitalId: number = 1510;
export const csDispatchTroopsId: number = 1511;
export const scDispatchTroopsId: number = 1512;
export const csWithdrawDefendingTroopsId: number = 1513;
export const scWithdrawDefendingTroopsId: number = 1514;
export const csHealInjuredHeroesId: number = 1515;
export const scHealInjuredHeroesId: number = 1516;
export const csHeroDeadListId: number = 1517;
export const scHeroDeadListId: number = 1518;
export const scCityBattleResultId: number = 1519;
