// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.33.5
// source: MessageCommon.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

/**
 * 本地gm质量
 * @Id(7000)
 */
export interface CsGmCmd {
  gmCode: string;
  params: string;
}

function createBaseCsGmCmd(): CsGmCmd {
  return { gmCode: "", params: "" };
}

export const CsGmCmd: MessageFns<CsGmCmd> = {
  encode(message: CsGmCmd, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.gmCode !== "") {
      writer.uint32(10).string(message.gmCode);
    }
    if (message.params !== "") {
      writer.uint32(18).string(message.params);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsGmCmd {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsGmCmd();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.gmCode = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsGmCmd {
    return {
      gmCode: isSet(object.gmCode) ? globalThis.String(object.gmCode) : "",
      params: isSet(object.params) ? globalThis.String(object.params) : "",
    };
  },

  toJSON(message: CsGmCmd): unknown {
    const obj: any = {};
    if (message.gmCode !== "") {
      obj.gmCode = message.gmCode;
    }
    if (message.params !== "") {
      obj.params = message.params;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsGmCmd>, I>>(base?: I): CsGmCmd {
    return CsGmCmd.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsGmCmd>, I>>(object: I): CsGmCmd {
    const message = createBaseCsGmCmd();
    message.gmCode = object.gmCode ?? "";
    message.params = object.params ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}

export const csGmCmdId: number = 7000;
