// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.33.5
// source: MessageCity.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { CityBattleDetail, CityInfo } from "./structure";

export const protobufPackage = "protobuf";

/**
 * 获取城池列表
 * @Id(1501)
 */
export interface CsGetCityList {
}

/**
 * 获取城池列表
 * @Id(1502)
 */
export interface ScGetCityList {
  cityInfos: CityInfo[];
}

/**
 * 获取城池详情
 * @Id(1503)
 */
export interface CsGetCityDetail {
  cityId: number;
}

/**
 * 获取城池详情
 * @Id(1504)
 */
export interface ScGetCityDetail {
  cityInfo?: CityInfo | undefined;
}

/**
 * 获取玩家城池的详情
 * @Id(1505)
 */
export interface CsPlayerCityInfo {
}

/**
 * 获取玩家城池的详情
 * @Id(1506)
 */
export interface ScPlayerCityInfo {
  /** 当前已经解锁的最大城池id */
  unlockedCityMaxId: number;
  /** 下一个城池需要的已经通关的副本 */
  nextUnlockInstanceIds: number[];
}

/**
 * 城战详细信息
 * @Id(1507)
 */
export interface CsCityBattleDetail {
  cityId: number;
}

/**
 * 城战详细信息
 * @Id(1508)
 */
export interface ScCityBattleDetail {
  detail?: CityBattleDetail | undefined;
}

function createBaseCsGetCityList(): CsGetCityList {
  return {};
}

export const CsGetCityList: MessageFns<CsGetCityList> = {
  encode(_: CsGetCityList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsGetCityList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsGetCityList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CsGetCityList {
    return {};
  },

  toJSON(_: CsGetCityList): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CsGetCityList>, I>>(base?: I): CsGetCityList {
    return CsGetCityList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsGetCityList>, I>>(_: I): CsGetCityList {
    const message = createBaseCsGetCityList();
    return message;
  },
};

function createBaseScGetCityList(): ScGetCityList {
  return { cityInfos: [] };
}

export const ScGetCityList: MessageFns<ScGetCityList> = {
  encode(message: ScGetCityList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.cityInfos) {
      CityInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScGetCityList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScGetCityList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cityInfos.push(CityInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScGetCityList {
    return {
      cityInfos: globalThis.Array.isArray(object?.cityInfos)
        ? object.cityInfos.map((e: any) => CityInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ScGetCityList): unknown {
    const obj: any = {};
    if (message.cityInfos?.length) {
      obj.cityInfos = message.cityInfos.map((e) => CityInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScGetCityList>, I>>(base?: I): ScGetCityList {
    return ScGetCityList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScGetCityList>, I>>(object: I): ScGetCityList {
    const message = createBaseScGetCityList();
    message.cityInfos = object.cityInfos?.map((e) => CityInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCsGetCityDetail(): CsGetCityDetail {
  return { cityId: 0 };
}

export const CsGetCityDetail: MessageFns<CsGetCityDetail> = {
  encode(message: CsGetCityDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cityId !== 0) {
      writer.uint32(8).int32(message.cityId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsGetCityDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsGetCityDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.cityId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsGetCityDetail {
    return { cityId: isSet(object.cityId) ? globalThis.Number(object.cityId) : 0 };
  },

  toJSON(message: CsGetCityDetail): unknown {
    const obj: any = {};
    if (message.cityId !== 0) {
      obj.cityId = Math.round(message.cityId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsGetCityDetail>, I>>(base?: I): CsGetCityDetail {
    return CsGetCityDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsGetCityDetail>, I>>(object: I): CsGetCityDetail {
    const message = createBaseCsGetCityDetail();
    message.cityId = object.cityId ?? 0;
    return message;
  },
};

function createBaseScGetCityDetail(): ScGetCityDetail {
  return { cityInfo: undefined };
}

export const ScGetCityDetail: MessageFns<ScGetCityDetail> = {
  encode(message: ScGetCityDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cityInfo !== undefined) {
      CityInfo.encode(message.cityInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScGetCityDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScGetCityDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cityInfo = CityInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScGetCityDetail {
    return { cityInfo: isSet(object.cityInfo) ? CityInfo.fromJSON(object.cityInfo) : undefined };
  },

  toJSON(message: ScGetCityDetail): unknown {
    const obj: any = {};
    if (message.cityInfo !== undefined) {
      obj.cityInfo = CityInfo.toJSON(message.cityInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScGetCityDetail>, I>>(base?: I): ScGetCityDetail {
    return ScGetCityDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScGetCityDetail>, I>>(object: I): ScGetCityDetail {
    const message = createBaseScGetCityDetail();
    message.cityInfo = (object.cityInfo !== undefined && object.cityInfo !== null)
      ? CityInfo.fromPartial(object.cityInfo)
      : undefined;
    return message;
  },
};

function createBaseCsPlayerCityInfo(): CsPlayerCityInfo {
  return {};
}

export const CsPlayerCityInfo: MessageFns<CsPlayerCityInfo> = {
  encode(_: CsPlayerCityInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsPlayerCityInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsPlayerCityInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CsPlayerCityInfo {
    return {};
  },

  toJSON(_: CsPlayerCityInfo): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CsPlayerCityInfo>, I>>(base?: I): CsPlayerCityInfo {
    return CsPlayerCityInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsPlayerCityInfo>, I>>(_: I): CsPlayerCityInfo {
    const message = createBaseCsPlayerCityInfo();
    return message;
  },
};

function createBaseScPlayerCityInfo(): ScPlayerCityInfo {
  return { unlockedCityMaxId: 0, nextUnlockInstanceIds: [] };
}

export const ScPlayerCityInfo: MessageFns<ScPlayerCityInfo> = {
  encode(message: ScPlayerCityInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.unlockedCityMaxId !== 0) {
      writer.uint32(8).int32(message.unlockedCityMaxId);
    }
    writer.uint32(18).fork();
    for (const v of message.nextUnlockInstanceIds) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScPlayerCityInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScPlayerCityInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.unlockedCityMaxId = reader.int32();
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.nextUnlockInstanceIds.push(reader.int32());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.nextUnlockInstanceIds.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScPlayerCityInfo {
    return {
      unlockedCityMaxId: isSet(object.unlockedCityMaxId) ? globalThis.Number(object.unlockedCityMaxId) : 0,
      nextUnlockInstanceIds: globalThis.Array.isArray(object?.nextUnlockInstanceIds)
        ? object.nextUnlockInstanceIds.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: ScPlayerCityInfo): unknown {
    const obj: any = {};
    if (message.unlockedCityMaxId !== 0) {
      obj.unlockedCityMaxId = Math.round(message.unlockedCityMaxId);
    }
    if (message.nextUnlockInstanceIds?.length) {
      obj.nextUnlockInstanceIds = message.nextUnlockInstanceIds.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScPlayerCityInfo>, I>>(base?: I): ScPlayerCityInfo {
    return ScPlayerCityInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScPlayerCityInfo>, I>>(object: I): ScPlayerCityInfo {
    const message = createBaseScPlayerCityInfo();
    message.unlockedCityMaxId = object.unlockedCityMaxId ?? 0;
    message.nextUnlockInstanceIds = object.nextUnlockInstanceIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseCsCityBattleDetail(): CsCityBattleDetail {
  return { cityId: 0 };
}

export const CsCityBattleDetail: MessageFns<CsCityBattleDetail> = {
  encode(message: CsCityBattleDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cityId !== 0) {
      writer.uint32(8).int32(message.cityId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsCityBattleDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsCityBattleDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.cityId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsCityBattleDetail {
    return { cityId: isSet(object.cityId) ? globalThis.Number(object.cityId) : 0 };
  },

  toJSON(message: CsCityBattleDetail): unknown {
    const obj: any = {};
    if (message.cityId !== 0) {
      obj.cityId = Math.round(message.cityId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsCityBattleDetail>, I>>(base?: I): CsCityBattleDetail {
    return CsCityBattleDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsCityBattleDetail>, I>>(object: I): CsCityBattleDetail {
    const message = createBaseCsCityBattleDetail();
    message.cityId = object.cityId ?? 0;
    return message;
  },
};

function createBaseScCityBattleDetail(): ScCityBattleDetail {
  return { detail: undefined };
}

export const ScCityBattleDetail: MessageFns<ScCityBattleDetail> = {
  encode(message: ScCityBattleDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.detail !== undefined) {
      CityBattleDetail.encode(message.detail, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScCityBattleDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScCityBattleDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.detail = CityBattleDetail.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScCityBattleDetail {
    return { detail: isSet(object.detail) ? CityBattleDetail.fromJSON(object.detail) : undefined };
  },

  toJSON(message: ScCityBattleDetail): unknown {
    const obj: any = {};
    if (message.detail !== undefined) {
      obj.detail = CityBattleDetail.toJSON(message.detail);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScCityBattleDetail>, I>>(base?: I): ScCityBattleDetail {
    return ScCityBattleDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScCityBattleDetail>, I>>(object: I): ScCityBattleDetail {
    const message = createBaseScCityBattleDetail();
    message.detail = (object.detail !== undefined && object.detail !== null)
      ? CityBattleDetail.fromPartial(object.detail)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}

export const csGetCityListId: number = 1501;
export const scGetCityListId: number = 1502;
export const csGetCityDetailId: number = 1503;
export const scGetCityDetailId: number = 1504;
export const csPlayerCityInfoId: number = 1505;
export const scPlayerCityInfoId: number = 1506;
export const csCityBattleDetailId: number = 1507;
export const scCityBattleDetailId: number = 1508;
