// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.33.5
// source: MessageLegion.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { LegionInfo, LegionListInfo, LegionMemberInfo } from "./structure";

export const protobufPackage = "protobuf";

/**
 * 创建军团
 * @Id(1301)
 */
export interface CsCreateLegion {
  name: string;
  banner: string;
  flagId: number;
}

/**
 * 创建军团
 * @Id(1302)
 */
export interface ScCreateLegion {
  legionInfo?: LegionInfo | undefined;
}

/**
 * 加入军团
 * @Id(1303)
 */
export interface CsApplyJoinLegion {
  legionId: string;
}

/**
 * 加入军团
 * @Id(1304)
 */
export interface ScApplyJoinLegion {
}

/**
 * 解散军团
 * @Id(1305)
 */
export interface CsDisbandLegion {
  legionId: string;
}

/**
 * 解散军团
 * @Id(1306)
 */
export interface ScDisbandLegion {
}

/**
 * 退出军团
 * @Id(1307)
 */
export interface CsLeaveLegion {
  legionId: string;
}

/**
 * 退出军团
 * @Id(1308)
 */
export interface ScLeaveLegion {
  legionMemberInfo?: LegionMemberInfo | undefined;
}

/**
 * 踢出成员
 * @Id(1309)
 */
export interface CsKickMember {
  targetPlayerId: string;
  legionId: string;
}

/**
 * 踢出成员
 * @Id(1310)
 */
export interface ScKickMember {
}

/**
 * 设置成员职位
 * @Id(1311)
 */
export interface CsSetMemberPosition {
  targetPlayerId: string;
  legionId: string;
  position: number;
}

/**
 * 设置成员职位
 * @Id(1312)
 */
export interface ScSetMemberPosition {
  legionMemberInfo?: LegionMemberInfo | undefined;
}

/**
 * 转让军团长
 * @Id(1313)
 */
export interface CsTransferLeader {
  targetPlayerId: string;
  legionId: string;
}

/**
 * 转让军团长
 * @Id(1314)
 */
export interface ScTransferLeader {
  legionInfo?: LegionInfo | undefined;
}

/**
 * 更新军团信息
 * @Id(1315)
 */
export interface CsUpdateLegionInfo {
  legionId: string;
  banner: string;
  flagId: number;
}

/**
 * 更新军团信息
 * @Id(1316)
 */
export interface ScUpdateLegionInfo {
  legionInfo?: LegionInfo | undefined;
}

/**
 * 更新军团公告
 * @Id(1317)
 */
export interface CsUpdateNotice {
  legionId: string;
  notice: string;
}

/**
 * 更新军团公告
 * @Id(1318)
 */
export interface ScUpdateNotice {
  legionInfo?: LegionInfo | undefined;
}

/**
 * 更新加入规则
 * @Id(1319)
 */
export interface CsUpdateJoinRule {
  legionId: string;
  condition: number;
  powerReq: string;
  levelReq: number;
}

/**
 * 更新加入规则
 * @Id(1320)
 */
export interface ScUpdateJoinRule {
  legionInfo?: LegionInfo | undefined;
}

/**
 * 升级军团
 * @Id(1321)
 */
export interface CsUpgradeLegion {
  legionId: string;
}

/**
 * 升级军团
 * @Id(1322)
 */
export interface ScUpgradeLegion {
  legionInfo?: LegionInfo | undefined;
}

/**
 * 获取军团列表
 * @Id(1323)
 */
export interface CsGetLegionList {
}

/**
 * 获取军团列表
 * @Id(1324)
 */
export interface ScGetLegionList {
  legionInfos: LegionListInfo[];
}

/**
 * 获取军团信息
 * @Id(1325)
 */
export interface CsGetLegionInfo {
  legionId: string;
}

/**
 * 获取军团信息
 * @Id(1326)
 */
export interface ScGetLegionInfo {
  legionInfo?: LegionInfo | undefined;
}

/**
 * 获取军团成员列表
 * @Id(1327)
 */
export interface CsGetLegionMemberList {
  legionId: string;
}

/**
 * 获取军团成员列表
 * @Id(1328)
 */
export interface ScGetLegionMemberList {
  legionMemberInfos: LegionMemberInfo[];
}

/**
 * 获取玩家军团信息
 * @Id(1329)
 */
export interface CsGetPlayerLegionInfo {
}

/**
 * 获取玩家军团信息
 * @Id(1330)
 */
export interface ScGetPlayerLegionInfo {
  legionMemberInfo?: LegionMemberInfo | undefined;
}

/**
 * 获取玩家军团信息
 * @Id(1331)
 */
export interface CsApproveApplication {
  legionId: string;
  applyPlayerId: string;
  approved: boolean;
}

/**
 * 获取玩家军团信息
 * @Id(1332)
 */
export interface ScApproveApplication {
}

function createBaseCsCreateLegion(): CsCreateLegion {
  return { name: "", banner: "", flagId: 0 };
}

export const CsCreateLegion: MessageFns<CsCreateLegion> = {
  encode(message: CsCreateLegion, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.banner !== "") {
      writer.uint32(18).string(message.banner);
    }
    if (message.flagId !== 0) {
      writer.uint32(24).int32(message.flagId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsCreateLegion {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsCreateLegion();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.banner = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.flagId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsCreateLegion {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      banner: isSet(object.banner) ? globalThis.String(object.banner) : "",
      flagId: isSet(object.flagId) ? globalThis.Number(object.flagId) : 0,
    };
  },

  toJSON(message: CsCreateLegion): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.banner !== "") {
      obj.banner = message.banner;
    }
    if (message.flagId !== 0) {
      obj.flagId = Math.round(message.flagId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsCreateLegion>, I>>(base?: I): CsCreateLegion {
    return CsCreateLegion.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsCreateLegion>, I>>(object: I): CsCreateLegion {
    const message = createBaseCsCreateLegion();
    message.name = object.name ?? "";
    message.banner = object.banner ?? "";
    message.flagId = object.flagId ?? 0;
    return message;
  },
};

function createBaseScCreateLegion(): ScCreateLegion {
  return { legionInfo: undefined };
}

export const ScCreateLegion: MessageFns<ScCreateLegion> = {
  encode(message: ScCreateLegion, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionInfo !== undefined) {
      LegionInfo.encode(message.legionInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScCreateLegion {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScCreateLegion();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionInfo = LegionInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScCreateLegion {
    return { legionInfo: isSet(object.legionInfo) ? LegionInfo.fromJSON(object.legionInfo) : undefined };
  },

  toJSON(message: ScCreateLegion): unknown {
    const obj: any = {};
    if (message.legionInfo !== undefined) {
      obj.legionInfo = LegionInfo.toJSON(message.legionInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScCreateLegion>, I>>(base?: I): ScCreateLegion {
    return ScCreateLegion.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScCreateLegion>, I>>(object: I): ScCreateLegion {
    const message = createBaseScCreateLegion();
    message.legionInfo = (object.legionInfo !== undefined && object.legionInfo !== null)
      ? LegionInfo.fromPartial(object.legionInfo)
      : undefined;
    return message;
  },
};

function createBaseCsApplyJoinLegion(): CsApplyJoinLegion {
  return { legionId: "" };
}

export const CsApplyJoinLegion: MessageFns<CsApplyJoinLegion> = {
  encode(message: CsApplyJoinLegion, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionId !== "") {
      writer.uint32(10).string(message.legionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsApplyJoinLegion {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsApplyJoinLegion();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsApplyJoinLegion {
    return { legionId: isSet(object.legionId) ? globalThis.String(object.legionId) : "" };
  },

  toJSON(message: CsApplyJoinLegion): unknown {
    const obj: any = {};
    if (message.legionId !== "") {
      obj.legionId = message.legionId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsApplyJoinLegion>, I>>(base?: I): CsApplyJoinLegion {
    return CsApplyJoinLegion.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsApplyJoinLegion>, I>>(object: I): CsApplyJoinLegion {
    const message = createBaseCsApplyJoinLegion();
    message.legionId = object.legionId ?? "";
    return message;
  },
};

function createBaseScApplyJoinLegion(): ScApplyJoinLegion {
  return {};
}

export const ScApplyJoinLegion: MessageFns<ScApplyJoinLegion> = {
  encode(_: ScApplyJoinLegion, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScApplyJoinLegion {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScApplyJoinLegion();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ScApplyJoinLegion {
    return {};
  },

  toJSON(_: ScApplyJoinLegion): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ScApplyJoinLegion>, I>>(base?: I): ScApplyJoinLegion {
    return ScApplyJoinLegion.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScApplyJoinLegion>, I>>(_: I): ScApplyJoinLegion {
    const message = createBaseScApplyJoinLegion();
    return message;
  },
};

function createBaseCsDisbandLegion(): CsDisbandLegion {
  return { legionId: "" };
}

export const CsDisbandLegion: MessageFns<CsDisbandLegion> = {
  encode(message: CsDisbandLegion, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionId !== "") {
      writer.uint32(10).string(message.legionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsDisbandLegion {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsDisbandLegion();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsDisbandLegion {
    return { legionId: isSet(object.legionId) ? globalThis.String(object.legionId) : "" };
  },

  toJSON(message: CsDisbandLegion): unknown {
    const obj: any = {};
    if (message.legionId !== "") {
      obj.legionId = message.legionId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsDisbandLegion>, I>>(base?: I): CsDisbandLegion {
    return CsDisbandLegion.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsDisbandLegion>, I>>(object: I): CsDisbandLegion {
    const message = createBaseCsDisbandLegion();
    message.legionId = object.legionId ?? "";
    return message;
  },
};

function createBaseScDisbandLegion(): ScDisbandLegion {
  return {};
}

export const ScDisbandLegion: MessageFns<ScDisbandLegion> = {
  encode(_: ScDisbandLegion, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScDisbandLegion {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScDisbandLegion();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ScDisbandLegion {
    return {};
  },

  toJSON(_: ScDisbandLegion): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ScDisbandLegion>, I>>(base?: I): ScDisbandLegion {
    return ScDisbandLegion.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScDisbandLegion>, I>>(_: I): ScDisbandLegion {
    const message = createBaseScDisbandLegion();
    return message;
  },
};

function createBaseCsLeaveLegion(): CsLeaveLegion {
  return { legionId: "" };
}

export const CsLeaveLegion: MessageFns<CsLeaveLegion> = {
  encode(message: CsLeaveLegion, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionId !== "") {
      writer.uint32(10).string(message.legionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsLeaveLegion {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsLeaveLegion();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsLeaveLegion {
    return { legionId: isSet(object.legionId) ? globalThis.String(object.legionId) : "" };
  },

  toJSON(message: CsLeaveLegion): unknown {
    const obj: any = {};
    if (message.legionId !== "") {
      obj.legionId = message.legionId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsLeaveLegion>, I>>(base?: I): CsLeaveLegion {
    return CsLeaveLegion.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsLeaveLegion>, I>>(object: I): CsLeaveLegion {
    const message = createBaseCsLeaveLegion();
    message.legionId = object.legionId ?? "";
    return message;
  },
};

function createBaseScLeaveLegion(): ScLeaveLegion {
  return { legionMemberInfo: undefined };
}

export const ScLeaveLegion: MessageFns<ScLeaveLegion> = {
  encode(message: ScLeaveLegion, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionMemberInfo !== undefined) {
      LegionMemberInfo.encode(message.legionMemberInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScLeaveLegion {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScLeaveLegion();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionMemberInfo = LegionMemberInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScLeaveLegion {
    return {
      legionMemberInfo: isSet(object.legionMemberInfo) ? LegionMemberInfo.fromJSON(object.legionMemberInfo) : undefined,
    };
  },

  toJSON(message: ScLeaveLegion): unknown {
    const obj: any = {};
    if (message.legionMemberInfo !== undefined) {
      obj.legionMemberInfo = LegionMemberInfo.toJSON(message.legionMemberInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScLeaveLegion>, I>>(base?: I): ScLeaveLegion {
    return ScLeaveLegion.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScLeaveLegion>, I>>(object: I): ScLeaveLegion {
    const message = createBaseScLeaveLegion();
    message.legionMemberInfo = (object.legionMemberInfo !== undefined && object.legionMemberInfo !== null)
      ? LegionMemberInfo.fromPartial(object.legionMemberInfo)
      : undefined;
    return message;
  },
};

function createBaseCsKickMember(): CsKickMember {
  return { targetPlayerId: "", legionId: "" };
}

export const CsKickMember: MessageFns<CsKickMember> = {
  encode(message: CsKickMember, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.targetPlayerId !== "") {
      writer.uint32(10).string(message.targetPlayerId);
    }
    if (message.legionId !== "") {
      writer.uint32(18).string(message.legionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsKickMember {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsKickMember();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.targetPlayerId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.legionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsKickMember {
    return {
      targetPlayerId: isSet(object.targetPlayerId) ? globalThis.String(object.targetPlayerId) : "",
      legionId: isSet(object.legionId) ? globalThis.String(object.legionId) : "",
    };
  },

  toJSON(message: CsKickMember): unknown {
    const obj: any = {};
    if (message.targetPlayerId !== "") {
      obj.targetPlayerId = message.targetPlayerId;
    }
    if (message.legionId !== "") {
      obj.legionId = message.legionId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsKickMember>, I>>(base?: I): CsKickMember {
    return CsKickMember.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsKickMember>, I>>(object: I): CsKickMember {
    const message = createBaseCsKickMember();
    message.targetPlayerId = object.targetPlayerId ?? "";
    message.legionId = object.legionId ?? "";
    return message;
  },
};

function createBaseScKickMember(): ScKickMember {
  return {};
}

export const ScKickMember: MessageFns<ScKickMember> = {
  encode(_: ScKickMember, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScKickMember {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScKickMember();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ScKickMember {
    return {};
  },

  toJSON(_: ScKickMember): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ScKickMember>, I>>(base?: I): ScKickMember {
    return ScKickMember.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScKickMember>, I>>(_: I): ScKickMember {
    const message = createBaseScKickMember();
    return message;
  },
};

function createBaseCsSetMemberPosition(): CsSetMemberPosition {
  return { targetPlayerId: "", legionId: "", position: 0 };
}

export const CsSetMemberPosition: MessageFns<CsSetMemberPosition> = {
  encode(message: CsSetMemberPosition, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.targetPlayerId !== "") {
      writer.uint32(10).string(message.targetPlayerId);
    }
    if (message.legionId !== "") {
      writer.uint32(18).string(message.legionId);
    }
    if (message.position !== 0) {
      writer.uint32(24).int32(message.position);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsSetMemberPosition {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsSetMemberPosition();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.targetPlayerId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.legionId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.position = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsSetMemberPosition {
    return {
      targetPlayerId: isSet(object.targetPlayerId) ? globalThis.String(object.targetPlayerId) : "",
      legionId: isSet(object.legionId) ? globalThis.String(object.legionId) : "",
      position: isSet(object.position) ? globalThis.Number(object.position) : 0,
    };
  },

  toJSON(message: CsSetMemberPosition): unknown {
    const obj: any = {};
    if (message.targetPlayerId !== "") {
      obj.targetPlayerId = message.targetPlayerId;
    }
    if (message.legionId !== "") {
      obj.legionId = message.legionId;
    }
    if (message.position !== 0) {
      obj.position = Math.round(message.position);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsSetMemberPosition>, I>>(base?: I): CsSetMemberPosition {
    return CsSetMemberPosition.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsSetMemberPosition>, I>>(object: I): CsSetMemberPosition {
    const message = createBaseCsSetMemberPosition();
    message.targetPlayerId = object.targetPlayerId ?? "";
    message.legionId = object.legionId ?? "";
    message.position = object.position ?? 0;
    return message;
  },
};

function createBaseScSetMemberPosition(): ScSetMemberPosition {
  return { legionMemberInfo: undefined };
}

export const ScSetMemberPosition: MessageFns<ScSetMemberPosition> = {
  encode(message: ScSetMemberPosition, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionMemberInfo !== undefined) {
      LegionMemberInfo.encode(message.legionMemberInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScSetMemberPosition {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScSetMemberPosition();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionMemberInfo = LegionMemberInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScSetMemberPosition {
    return {
      legionMemberInfo: isSet(object.legionMemberInfo) ? LegionMemberInfo.fromJSON(object.legionMemberInfo) : undefined,
    };
  },

  toJSON(message: ScSetMemberPosition): unknown {
    const obj: any = {};
    if (message.legionMemberInfo !== undefined) {
      obj.legionMemberInfo = LegionMemberInfo.toJSON(message.legionMemberInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScSetMemberPosition>, I>>(base?: I): ScSetMemberPosition {
    return ScSetMemberPosition.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScSetMemberPosition>, I>>(object: I): ScSetMemberPosition {
    const message = createBaseScSetMemberPosition();
    message.legionMemberInfo = (object.legionMemberInfo !== undefined && object.legionMemberInfo !== null)
      ? LegionMemberInfo.fromPartial(object.legionMemberInfo)
      : undefined;
    return message;
  },
};

function createBaseCsTransferLeader(): CsTransferLeader {
  return { targetPlayerId: "", legionId: "" };
}

export const CsTransferLeader: MessageFns<CsTransferLeader> = {
  encode(message: CsTransferLeader, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.targetPlayerId !== "") {
      writer.uint32(10).string(message.targetPlayerId);
    }
    if (message.legionId !== "") {
      writer.uint32(18).string(message.legionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsTransferLeader {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsTransferLeader();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.targetPlayerId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.legionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsTransferLeader {
    return {
      targetPlayerId: isSet(object.targetPlayerId) ? globalThis.String(object.targetPlayerId) : "",
      legionId: isSet(object.legionId) ? globalThis.String(object.legionId) : "",
    };
  },

  toJSON(message: CsTransferLeader): unknown {
    const obj: any = {};
    if (message.targetPlayerId !== "") {
      obj.targetPlayerId = message.targetPlayerId;
    }
    if (message.legionId !== "") {
      obj.legionId = message.legionId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsTransferLeader>, I>>(base?: I): CsTransferLeader {
    return CsTransferLeader.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsTransferLeader>, I>>(object: I): CsTransferLeader {
    const message = createBaseCsTransferLeader();
    message.targetPlayerId = object.targetPlayerId ?? "";
    message.legionId = object.legionId ?? "";
    return message;
  },
};

function createBaseScTransferLeader(): ScTransferLeader {
  return { legionInfo: undefined };
}

export const ScTransferLeader: MessageFns<ScTransferLeader> = {
  encode(message: ScTransferLeader, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionInfo !== undefined) {
      LegionInfo.encode(message.legionInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScTransferLeader {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScTransferLeader();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionInfo = LegionInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScTransferLeader {
    return { legionInfo: isSet(object.legionInfo) ? LegionInfo.fromJSON(object.legionInfo) : undefined };
  },

  toJSON(message: ScTransferLeader): unknown {
    const obj: any = {};
    if (message.legionInfo !== undefined) {
      obj.legionInfo = LegionInfo.toJSON(message.legionInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScTransferLeader>, I>>(base?: I): ScTransferLeader {
    return ScTransferLeader.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScTransferLeader>, I>>(object: I): ScTransferLeader {
    const message = createBaseScTransferLeader();
    message.legionInfo = (object.legionInfo !== undefined && object.legionInfo !== null)
      ? LegionInfo.fromPartial(object.legionInfo)
      : undefined;
    return message;
  },
};

function createBaseCsUpdateLegionInfo(): CsUpdateLegionInfo {
  return { legionId: "", banner: "", flagId: 0 };
}

export const CsUpdateLegionInfo: MessageFns<CsUpdateLegionInfo> = {
  encode(message: CsUpdateLegionInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionId !== "") {
      writer.uint32(10).string(message.legionId);
    }
    if (message.banner !== "") {
      writer.uint32(18).string(message.banner);
    }
    if (message.flagId !== 0) {
      writer.uint32(24).int32(message.flagId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsUpdateLegionInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsUpdateLegionInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.banner = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.flagId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsUpdateLegionInfo {
    return {
      legionId: isSet(object.legionId) ? globalThis.String(object.legionId) : "",
      banner: isSet(object.banner) ? globalThis.String(object.banner) : "",
      flagId: isSet(object.flagId) ? globalThis.Number(object.flagId) : 0,
    };
  },

  toJSON(message: CsUpdateLegionInfo): unknown {
    const obj: any = {};
    if (message.legionId !== "") {
      obj.legionId = message.legionId;
    }
    if (message.banner !== "") {
      obj.banner = message.banner;
    }
    if (message.flagId !== 0) {
      obj.flagId = Math.round(message.flagId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsUpdateLegionInfo>, I>>(base?: I): CsUpdateLegionInfo {
    return CsUpdateLegionInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsUpdateLegionInfo>, I>>(object: I): CsUpdateLegionInfo {
    const message = createBaseCsUpdateLegionInfo();
    message.legionId = object.legionId ?? "";
    message.banner = object.banner ?? "";
    message.flagId = object.flagId ?? 0;
    return message;
  },
};

function createBaseScUpdateLegionInfo(): ScUpdateLegionInfo {
  return { legionInfo: undefined };
}

export const ScUpdateLegionInfo: MessageFns<ScUpdateLegionInfo> = {
  encode(message: ScUpdateLegionInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionInfo !== undefined) {
      LegionInfo.encode(message.legionInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScUpdateLegionInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScUpdateLegionInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionInfo = LegionInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScUpdateLegionInfo {
    return { legionInfo: isSet(object.legionInfo) ? LegionInfo.fromJSON(object.legionInfo) : undefined };
  },

  toJSON(message: ScUpdateLegionInfo): unknown {
    const obj: any = {};
    if (message.legionInfo !== undefined) {
      obj.legionInfo = LegionInfo.toJSON(message.legionInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScUpdateLegionInfo>, I>>(base?: I): ScUpdateLegionInfo {
    return ScUpdateLegionInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScUpdateLegionInfo>, I>>(object: I): ScUpdateLegionInfo {
    const message = createBaseScUpdateLegionInfo();
    message.legionInfo = (object.legionInfo !== undefined && object.legionInfo !== null)
      ? LegionInfo.fromPartial(object.legionInfo)
      : undefined;
    return message;
  },
};

function createBaseCsUpdateNotice(): CsUpdateNotice {
  return { legionId: "", notice: "" };
}

export const CsUpdateNotice: MessageFns<CsUpdateNotice> = {
  encode(message: CsUpdateNotice, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionId !== "") {
      writer.uint32(10).string(message.legionId);
    }
    if (message.notice !== "") {
      writer.uint32(18).string(message.notice);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsUpdateNotice {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsUpdateNotice();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.notice = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsUpdateNotice {
    return {
      legionId: isSet(object.legionId) ? globalThis.String(object.legionId) : "",
      notice: isSet(object.notice) ? globalThis.String(object.notice) : "",
    };
  },

  toJSON(message: CsUpdateNotice): unknown {
    const obj: any = {};
    if (message.legionId !== "") {
      obj.legionId = message.legionId;
    }
    if (message.notice !== "") {
      obj.notice = message.notice;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsUpdateNotice>, I>>(base?: I): CsUpdateNotice {
    return CsUpdateNotice.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsUpdateNotice>, I>>(object: I): CsUpdateNotice {
    const message = createBaseCsUpdateNotice();
    message.legionId = object.legionId ?? "";
    message.notice = object.notice ?? "";
    return message;
  },
};

function createBaseScUpdateNotice(): ScUpdateNotice {
  return { legionInfo: undefined };
}

export const ScUpdateNotice: MessageFns<ScUpdateNotice> = {
  encode(message: ScUpdateNotice, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionInfo !== undefined) {
      LegionInfo.encode(message.legionInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScUpdateNotice {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScUpdateNotice();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionInfo = LegionInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScUpdateNotice {
    return { legionInfo: isSet(object.legionInfo) ? LegionInfo.fromJSON(object.legionInfo) : undefined };
  },

  toJSON(message: ScUpdateNotice): unknown {
    const obj: any = {};
    if (message.legionInfo !== undefined) {
      obj.legionInfo = LegionInfo.toJSON(message.legionInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScUpdateNotice>, I>>(base?: I): ScUpdateNotice {
    return ScUpdateNotice.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScUpdateNotice>, I>>(object: I): ScUpdateNotice {
    const message = createBaseScUpdateNotice();
    message.legionInfo = (object.legionInfo !== undefined && object.legionInfo !== null)
      ? LegionInfo.fromPartial(object.legionInfo)
      : undefined;
    return message;
  },
};

function createBaseCsUpdateJoinRule(): CsUpdateJoinRule {
  return { legionId: "", condition: 0, powerReq: "", levelReq: 0 };
}

export const CsUpdateJoinRule: MessageFns<CsUpdateJoinRule> = {
  encode(message: CsUpdateJoinRule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionId !== "") {
      writer.uint32(10).string(message.legionId);
    }
    if (message.condition !== 0) {
      writer.uint32(16).int32(message.condition);
    }
    if (message.powerReq !== "") {
      writer.uint32(26).string(message.powerReq);
    }
    if (message.levelReq !== 0) {
      writer.uint32(32).int32(message.levelReq);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsUpdateJoinRule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsUpdateJoinRule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.condition = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.powerReq = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.levelReq = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsUpdateJoinRule {
    return {
      legionId: isSet(object.legionId) ? globalThis.String(object.legionId) : "",
      condition: isSet(object.condition) ? globalThis.Number(object.condition) : 0,
      powerReq: isSet(object.powerReq) ? globalThis.String(object.powerReq) : "",
      levelReq: isSet(object.levelReq) ? globalThis.Number(object.levelReq) : 0,
    };
  },

  toJSON(message: CsUpdateJoinRule): unknown {
    const obj: any = {};
    if (message.legionId !== "") {
      obj.legionId = message.legionId;
    }
    if (message.condition !== 0) {
      obj.condition = Math.round(message.condition);
    }
    if (message.powerReq !== "") {
      obj.powerReq = message.powerReq;
    }
    if (message.levelReq !== 0) {
      obj.levelReq = Math.round(message.levelReq);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsUpdateJoinRule>, I>>(base?: I): CsUpdateJoinRule {
    return CsUpdateJoinRule.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsUpdateJoinRule>, I>>(object: I): CsUpdateJoinRule {
    const message = createBaseCsUpdateJoinRule();
    message.legionId = object.legionId ?? "";
    message.condition = object.condition ?? 0;
    message.powerReq = object.powerReq ?? "";
    message.levelReq = object.levelReq ?? 0;
    return message;
  },
};

function createBaseScUpdateJoinRule(): ScUpdateJoinRule {
  return { legionInfo: undefined };
}

export const ScUpdateJoinRule: MessageFns<ScUpdateJoinRule> = {
  encode(message: ScUpdateJoinRule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionInfo !== undefined) {
      LegionInfo.encode(message.legionInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScUpdateJoinRule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScUpdateJoinRule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionInfo = LegionInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScUpdateJoinRule {
    return { legionInfo: isSet(object.legionInfo) ? LegionInfo.fromJSON(object.legionInfo) : undefined };
  },

  toJSON(message: ScUpdateJoinRule): unknown {
    const obj: any = {};
    if (message.legionInfo !== undefined) {
      obj.legionInfo = LegionInfo.toJSON(message.legionInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScUpdateJoinRule>, I>>(base?: I): ScUpdateJoinRule {
    return ScUpdateJoinRule.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScUpdateJoinRule>, I>>(object: I): ScUpdateJoinRule {
    const message = createBaseScUpdateJoinRule();
    message.legionInfo = (object.legionInfo !== undefined && object.legionInfo !== null)
      ? LegionInfo.fromPartial(object.legionInfo)
      : undefined;
    return message;
  },
};

function createBaseCsUpgradeLegion(): CsUpgradeLegion {
  return { legionId: "" };
}

export const CsUpgradeLegion: MessageFns<CsUpgradeLegion> = {
  encode(message: CsUpgradeLegion, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionId !== "") {
      writer.uint32(10).string(message.legionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsUpgradeLegion {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsUpgradeLegion();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsUpgradeLegion {
    return { legionId: isSet(object.legionId) ? globalThis.String(object.legionId) : "" };
  },

  toJSON(message: CsUpgradeLegion): unknown {
    const obj: any = {};
    if (message.legionId !== "") {
      obj.legionId = message.legionId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsUpgradeLegion>, I>>(base?: I): CsUpgradeLegion {
    return CsUpgradeLegion.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsUpgradeLegion>, I>>(object: I): CsUpgradeLegion {
    const message = createBaseCsUpgradeLegion();
    message.legionId = object.legionId ?? "";
    return message;
  },
};

function createBaseScUpgradeLegion(): ScUpgradeLegion {
  return { legionInfo: undefined };
}

export const ScUpgradeLegion: MessageFns<ScUpgradeLegion> = {
  encode(message: ScUpgradeLegion, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionInfo !== undefined) {
      LegionInfo.encode(message.legionInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScUpgradeLegion {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScUpgradeLegion();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionInfo = LegionInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScUpgradeLegion {
    return { legionInfo: isSet(object.legionInfo) ? LegionInfo.fromJSON(object.legionInfo) : undefined };
  },

  toJSON(message: ScUpgradeLegion): unknown {
    const obj: any = {};
    if (message.legionInfo !== undefined) {
      obj.legionInfo = LegionInfo.toJSON(message.legionInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScUpgradeLegion>, I>>(base?: I): ScUpgradeLegion {
    return ScUpgradeLegion.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScUpgradeLegion>, I>>(object: I): ScUpgradeLegion {
    const message = createBaseScUpgradeLegion();
    message.legionInfo = (object.legionInfo !== undefined && object.legionInfo !== null)
      ? LegionInfo.fromPartial(object.legionInfo)
      : undefined;
    return message;
  },
};

function createBaseCsGetLegionList(): CsGetLegionList {
  return {};
}

export const CsGetLegionList: MessageFns<CsGetLegionList> = {
  encode(_: CsGetLegionList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsGetLegionList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsGetLegionList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CsGetLegionList {
    return {};
  },

  toJSON(_: CsGetLegionList): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CsGetLegionList>, I>>(base?: I): CsGetLegionList {
    return CsGetLegionList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsGetLegionList>, I>>(_: I): CsGetLegionList {
    const message = createBaseCsGetLegionList();
    return message;
  },
};

function createBaseScGetLegionList(): ScGetLegionList {
  return { legionInfos: [] };
}

export const ScGetLegionList: MessageFns<ScGetLegionList> = {
  encode(message: ScGetLegionList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.legionInfos) {
      LegionListInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScGetLegionList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScGetLegionList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionInfos.push(LegionListInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScGetLegionList {
    return {
      legionInfos: globalThis.Array.isArray(object?.legionInfos)
        ? object.legionInfos.map((e: any) => LegionListInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ScGetLegionList): unknown {
    const obj: any = {};
    if (message.legionInfos?.length) {
      obj.legionInfos = message.legionInfos.map((e) => LegionListInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScGetLegionList>, I>>(base?: I): ScGetLegionList {
    return ScGetLegionList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScGetLegionList>, I>>(object: I): ScGetLegionList {
    const message = createBaseScGetLegionList();
    message.legionInfos = object.legionInfos?.map((e) => LegionListInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCsGetLegionInfo(): CsGetLegionInfo {
  return { legionId: "" };
}

export const CsGetLegionInfo: MessageFns<CsGetLegionInfo> = {
  encode(message: CsGetLegionInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionId !== "") {
      writer.uint32(10).string(message.legionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsGetLegionInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsGetLegionInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsGetLegionInfo {
    return { legionId: isSet(object.legionId) ? globalThis.String(object.legionId) : "" };
  },

  toJSON(message: CsGetLegionInfo): unknown {
    const obj: any = {};
    if (message.legionId !== "") {
      obj.legionId = message.legionId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsGetLegionInfo>, I>>(base?: I): CsGetLegionInfo {
    return CsGetLegionInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsGetLegionInfo>, I>>(object: I): CsGetLegionInfo {
    const message = createBaseCsGetLegionInfo();
    message.legionId = object.legionId ?? "";
    return message;
  },
};

function createBaseScGetLegionInfo(): ScGetLegionInfo {
  return { legionInfo: undefined };
}

export const ScGetLegionInfo: MessageFns<ScGetLegionInfo> = {
  encode(message: ScGetLegionInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionInfo !== undefined) {
      LegionInfo.encode(message.legionInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScGetLegionInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScGetLegionInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionInfo = LegionInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScGetLegionInfo {
    return { legionInfo: isSet(object.legionInfo) ? LegionInfo.fromJSON(object.legionInfo) : undefined };
  },

  toJSON(message: ScGetLegionInfo): unknown {
    const obj: any = {};
    if (message.legionInfo !== undefined) {
      obj.legionInfo = LegionInfo.toJSON(message.legionInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScGetLegionInfo>, I>>(base?: I): ScGetLegionInfo {
    return ScGetLegionInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScGetLegionInfo>, I>>(object: I): ScGetLegionInfo {
    const message = createBaseScGetLegionInfo();
    message.legionInfo = (object.legionInfo !== undefined && object.legionInfo !== null)
      ? LegionInfo.fromPartial(object.legionInfo)
      : undefined;
    return message;
  },
};

function createBaseCsGetLegionMemberList(): CsGetLegionMemberList {
  return { legionId: "" };
}

export const CsGetLegionMemberList: MessageFns<CsGetLegionMemberList> = {
  encode(message: CsGetLegionMemberList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionId !== "") {
      writer.uint32(10).string(message.legionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsGetLegionMemberList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsGetLegionMemberList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsGetLegionMemberList {
    return { legionId: isSet(object.legionId) ? globalThis.String(object.legionId) : "" };
  },

  toJSON(message: CsGetLegionMemberList): unknown {
    const obj: any = {};
    if (message.legionId !== "") {
      obj.legionId = message.legionId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsGetLegionMemberList>, I>>(base?: I): CsGetLegionMemberList {
    return CsGetLegionMemberList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsGetLegionMemberList>, I>>(object: I): CsGetLegionMemberList {
    const message = createBaseCsGetLegionMemberList();
    message.legionId = object.legionId ?? "";
    return message;
  },
};

function createBaseScGetLegionMemberList(): ScGetLegionMemberList {
  return { legionMemberInfos: [] };
}

export const ScGetLegionMemberList: MessageFns<ScGetLegionMemberList> = {
  encode(message: ScGetLegionMemberList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.legionMemberInfos) {
      LegionMemberInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScGetLegionMemberList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScGetLegionMemberList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionMemberInfos.push(LegionMemberInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScGetLegionMemberList {
    return {
      legionMemberInfos: globalThis.Array.isArray(object?.legionMemberInfos)
        ? object.legionMemberInfos.map((e: any) => LegionMemberInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ScGetLegionMemberList): unknown {
    const obj: any = {};
    if (message.legionMemberInfos?.length) {
      obj.legionMemberInfos = message.legionMemberInfos.map((e) => LegionMemberInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScGetLegionMemberList>, I>>(base?: I): ScGetLegionMemberList {
    return ScGetLegionMemberList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScGetLegionMemberList>, I>>(object: I): ScGetLegionMemberList {
    const message = createBaseScGetLegionMemberList();
    message.legionMemberInfos = object.legionMemberInfos?.map((e) => LegionMemberInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCsGetPlayerLegionInfo(): CsGetPlayerLegionInfo {
  return {};
}

export const CsGetPlayerLegionInfo: MessageFns<CsGetPlayerLegionInfo> = {
  encode(_: CsGetPlayerLegionInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsGetPlayerLegionInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsGetPlayerLegionInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CsGetPlayerLegionInfo {
    return {};
  },

  toJSON(_: CsGetPlayerLegionInfo): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CsGetPlayerLegionInfo>, I>>(base?: I): CsGetPlayerLegionInfo {
    return CsGetPlayerLegionInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsGetPlayerLegionInfo>, I>>(_: I): CsGetPlayerLegionInfo {
    const message = createBaseCsGetPlayerLegionInfo();
    return message;
  },
};

function createBaseScGetPlayerLegionInfo(): ScGetPlayerLegionInfo {
  return { legionMemberInfo: undefined };
}

export const ScGetPlayerLegionInfo: MessageFns<ScGetPlayerLegionInfo> = {
  encode(message: ScGetPlayerLegionInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionMemberInfo !== undefined) {
      LegionMemberInfo.encode(message.legionMemberInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScGetPlayerLegionInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScGetPlayerLegionInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionMemberInfo = LegionMemberInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScGetPlayerLegionInfo {
    return {
      legionMemberInfo: isSet(object.legionMemberInfo) ? LegionMemberInfo.fromJSON(object.legionMemberInfo) : undefined,
    };
  },

  toJSON(message: ScGetPlayerLegionInfo): unknown {
    const obj: any = {};
    if (message.legionMemberInfo !== undefined) {
      obj.legionMemberInfo = LegionMemberInfo.toJSON(message.legionMemberInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScGetPlayerLegionInfo>, I>>(base?: I): ScGetPlayerLegionInfo {
    return ScGetPlayerLegionInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScGetPlayerLegionInfo>, I>>(object: I): ScGetPlayerLegionInfo {
    const message = createBaseScGetPlayerLegionInfo();
    message.legionMemberInfo = (object.legionMemberInfo !== undefined && object.legionMemberInfo !== null)
      ? LegionMemberInfo.fromPartial(object.legionMemberInfo)
      : undefined;
    return message;
  },
};

function createBaseCsApproveApplication(): CsApproveApplication {
  return { legionId: "", applyPlayerId: "", approved: false };
}

export const CsApproveApplication: MessageFns<CsApproveApplication> = {
  encode(message: CsApproveApplication, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionId !== "") {
      writer.uint32(10).string(message.legionId);
    }
    if (message.applyPlayerId !== "") {
      writer.uint32(18).string(message.applyPlayerId);
    }
    if (message.approved !== false) {
      writer.uint32(24).bool(message.approved);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsApproveApplication {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsApproveApplication();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.applyPlayerId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.approved = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsApproveApplication {
    return {
      legionId: isSet(object.legionId) ? globalThis.String(object.legionId) : "",
      applyPlayerId: isSet(object.applyPlayerId) ? globalThis.String(object.applyPlayerId) : "",
      approved: isSet(object.approved) ? globalThis.Boolean(object.approved) : false,
    };
  },

  toJSON(message: CsApproveApplication): unknown {
    const obj: any = {};
    if (message.legionId !== "") {
      obj.legionId = message.legionId;
    }
    if (message.applyPlayerId !== "") {
      obj.applyPlayerId = message.applyPlayerId;
    }
    if (message.approved !== false) {
      obj.approved = message.approved;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsApproveApplication>, I>>(base?: I): CsApproveApplication {
    return CsApproveApplication.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsApproveApplication>, I>>(object: I): CsApproveApplication {
    const message = createBaseCsApproveApplication();
    message.legionId = object.legionId ?? "";
    message.applyPlayerId = object.applyPlayerId ?? "";
    message.approved = object.approved ?? false;
    return message;
  },
};

function createBaseScApproveApplication(): ScApproveApplication {
  return {};
}

export const ScApproveApplication: MessageFns<ScApproveApplication> = {
  encode(_: ScApproveApplication, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScApproveApplication {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScApproveApplication();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ScApproveApplication {
    return {};
  },

  toJSON(_: ScApproveApplication): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ScApproveApplication>, I>>(base?: I): ScApproveApplication {
    return ScApproveApplication.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScApproveApplication>, I>>(_: I): ScApproveApplication {
    const message = createBaseScApproveApplication();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}

export const csCreateLegionId: number = 1301;
export const scCreateLegionId: number = 1302;
export const csApplyJoinLegionId: number = 1303;
export const scApplyJoinLegionId: number = 1304;
export const csDisbandLegionId: number = 1305;
export const scDisbandLegionId: number = 1306;
export const csLeaveLegionId: number = 1307;
export const scLeaveLegionId: number = 1308;
export const csKickMemberId: number = 1309;
export const scKickMemberId: number = 1310;
export const csSetMemberPositionId: number = 1311;
export const scSetMemberPositionId: number = 1312;
export const csTransferLeaderId: number = 1313;
export const scTransferLeaderId: number = 1314;
export const csUpdateLegionInfoId: number = 1315;
export const scUpdateLegionInfoId: number = 1316;
export const csUpdateNoticeId: number = 1317;
export const scUpdateNoticeId: number = 1318;
export const csUpdateJoinRuleId: number = 1319;
export const scUpdateJoinRuleId: number = 1320;
export const csUpgradeLegionId: number = 1321;
export const scUpgradeLegionId: number = 1322;
export const csGetLegionListId: number = 1323;
export const scGetLegionListId: number = 1324;
export const csGetLegionInfoId: number = 1325;
export const scGetLegionInfoId: number = 1326;
export const csGetLegionMemberListId: number = 1327;
export const scGetLegionMemberListId: number = 1328;
export const csGetPlayerLegionInfoId: number = 1329;
export const scGetPlayerLegionInfoId: number = 1330;
export const csApproveApplicationId: number = 1331;
export const scApproveApplicationId: number = 1332;
