// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.33.5
// source: MessageItem.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ItemInfo } from "./structure";

export const protobufPackage = "protobuf";

/**
 * 获取道具信息
 * @Id(1101)
 */
export interface CsGetItems {
}

/**
 * 获取道具信息
 * @Id(1102)
 */
export interface ScGetItems {
  itemInfo: ItemInfo[];
}

/**
 * 推送道具信息
 * @Id(1103)
 */
export interface ScUpdateItems {
  itemInfo: ItemInfo[];
}

function createBaseCsGetItems(): CsGetItems {
  return {};
}

export const CsGetItems: MessageFns<CsGetItems> = {
  encode(_: CsGetItems, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsGetItems {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsGetItems();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CsGetItems {
    return {};
  },

  toJSON(_: CsGetItems): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CsGetItems>, I>>(base?: I): CsGetItems {
    return CsGetItems.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsGetItems>, I>>(_: I): CsGetItems {
    const message = createBaseCsGetItems();
    return message;
  },
};

function createBaseScGetItems(): ScGetItems {
  return { itemInfo: [] };
}

export const ScGetItems: MessageFns<ScGetItems> = {
  encode(message: ScGetItems, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.itemInfo) {
      ItemInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScGetItems {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScGetItems();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.itemInfo.push(ItemInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScGetItems {
    return {
      itemInfo: globalThis.Array.isArray(object?.itemInfo) ? object.itemInfo.map((e: any) => ItemInfo.fromJSON(e)) : [],
    };
  },

  toJSON(message: ScGetItems): unknown {
    const obj: any = {};
    if (message.itemInfo?.length) {
      obj.itemInfo = message.itemInfo.map((e) => ItemInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScGetItems>, I>>(base?: I): ScGetItems {
    return ScGetItems.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScGetItems>, I>>(object: I): ScGetItems {
    const message = createBaseScGetItems();
    message.itemInfo = object.itemInfo?.map((e) => ItemInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseScUpdateItems(): ScUpdateItems {
  return { itemInfo: [] };
}

export const ScUpdateItems: MessageFns<ScUpdateItems> = {
  encode(message: ScUpdateItems, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.itemInfo) {
      ItemInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScUpdateItems {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScUpdateItems();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.itemInfo.push(ItemInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScUpdateItems {
    return {
      itemInfo: globalThis.Array.isArray(object?.itemInfo) ? object.itemInfo.map((e: any) => ItemInfo.fromJSON(e)) : [],
    };
  },

  toJSON(message: ScUpdateItems): unknown {
    const obj: any = {};
    if (message.itemInfo?.length) {
      obj.itemInfo = message.itemInfo.map((e) => ItemInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScUpdateItems>, I>>(base?: I): ScUpdateItems {
    return ScUpdateItems.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScUpdateItems>, I>>(object: I): ScUpdateItems {
    const message = createBaseScUpdateItems();
    message.itemInfo = object.itemInfo?.map((e) => ItemInfo.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}

export const csGetItemsId: number = 1101;
export const scGetItemsId: number = 1102;
export const scUpdateItemsId: number = 1103;
