// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.33.5
// source: MessageHero.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { HeroInfo } from "./structure";

export const protobufPackage = "protobuf";

/**
 * 获取单个武将信息
 * @Id(1001)
 */
export interface CsGetHero {
  heroTableId: number;
}

/**
 * 获取单个武将信息
 * @Id(1002)
 */
export interface ScGetHero {
  heroInfo?: HeroInfo | undefined;
}

/**
 * 获取玩家全部武将
 * @Id(1003)
 */
export interface CsGetPlayerHeroes {
}

/**
 * 获取玩家全部武将
 * @Id(1004)
 */
export interface ScGetPlayerHeroes {
  heroInfos: HeroInfo[];
}

/**
 * 获取玩家武将数量
 * @Id(1005)
 */
export interface CsGetPlayerHeroCount {
}

/**
 * 获取玩家武将数量
 * @Id(1006)
 */
export interface ScGetPlayerHeroCount {
  heroCount: number;
}

/**
 * 激活武将
 * @Id(1007)
 */
export interface CsActivateHero {
  heroTableId: number;
}

/**
 * 激活武将
 * @Id(1008)
 */
export interface ScActivateHero {
  heroInfo?: HeroInfo | undefined;
}

/**
 * 武将升星
 * @Id(1009)
 */
export interface CsUpgradeStar {
  heroTableId: number;
}

/**
 * 武将升星
 * @Id(1010)
 */
export interface ScUpgradeStar {
  heroInfo?: HeroInfo | undefined;
}

/**
 * 武将升级
 * @Id(1011)
 */
export interface CsUpgradeLevel {
  heroTableId: number;
  addLv: number;
}

/**
 * 武将升级
 * @Id(1012)
 */
export interface ScUpgradeLevel {
  heroInfo?: HeroInfo | undefined;
}

/**
 * 武将一键升级
 * @Id(1013)
 */
export interface CsUpgradeLevelAuto {
  heroTableId: number;
}

/**
 * 武将一键升级
 * @Id(1014)
 */
export interface ScUpgradeLevelAuto {
  heroInfo?: HeroInfo | undefined;
}

/**
 * 激活训练位
 * @Id(1015)
 */
export interface CsActivateTrain {
  heroTableId: number;
  trainIndex: number;
}

/**
 * 激活训练位
 * @Id(1016)
 */
export interface ScActivateTrain {
  heroInfo?: HeroInfo | undefined;
}

/**
 * 武将兵种进阶
 * @Id(1017)
 */
export interface CsUpgradeJobRank {
  heroTableId: number;
}

/**
 * 武将兵种进阶
 * @Id(1018)
 */
export interface ScUpgradeJobRank {
  heroInfo?: HeroInfo | undefined;
}

/**
 * 武将技能升级
 * @Id(1019)
 */
export interface CsUpgradeSkill {
  heroTableId: number;
  skillIndex: number;
}

/**
 * 武将技能升级
 * @Id(1020)
 */
export interface ScUpgradeSkill {
  heroInfo?: HeroInfo | undefined;
}

function createBaseCsGetHero(): CsGetHero {
  return { heroTableId: 0 };
}

export const CsGetHero: MessageFns<CsGetHero> = {
  encode(message: CsGetHero, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.heroTableId !== 0) {
      writer.uint32(8).int32(message.heroTableId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsGetHero {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsGetHero();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.heroTableId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsGetHero {
    return { heroTableId: isSet(object.heroTableId) ? globalThis.Number(object.heroTableId) : 0 };
  },

  toJSON(message: CsGetHero): unknown {
    const obj: any = {};
    if (message.heroTableId !== 0) {
      obj.heroTableId = Math.round(message.heroTableId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsGetHero>, I>>(base?: I): CsGetHero {
    return CsGetHero.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsGetHero>, I>>(object: I): CsGetHero {
    const message = createBaseCsGetHero();
    message.heroTableId = object.heroTableId ?? 0;
    return message;
  },
};

function createBaseScGetHero(): ScGetHero {
  return { heroInfo: undefined };
}

export const ScGetHero: MessageFns<ScGetHero> = {
  encode(message: ScGetHero, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.heroInfo !== undefined) {
      HeroInfo.encode(message.heroInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScGetHero {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScGetHero();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.heroInfo = HeroInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScGetHero {
    return { heroInfo: isSet(object.heroInfo) ? HeroInfo.fromJSON(object.heroInfo) : undefined };
  },

  toJSON(message: ScGetHero): unknown {
    const obj: any = {};
    if (message.heroInfo !== undefined) {
      obj.heroInfo = HeroInfo.toJSON(message.heroInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScGetHero>, I>>(base?: I): ScGetHero {
    return ScGetHero.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScGetHero>, I>>(object: I): ScGetHero {
    const message = createBaseScGetHero();
    message.heroInfo = (object.heroInfo !== undefined && object.heroInfo !== null)
      ? HeroInfo.fromPartial(object.heroInfo)
      : undefined;
    return message;
  },
};

function createBaseCsGetPlayerHeroes(): CsGetPlayerHeroes {
  return {};
}

export const CsGetPlayerHeroes: MessageFns<CsGetPlayerHeroes> = {
  encode(_: CsGetPlayerHeroes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsGetPlayerHeroes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsGetPlayerHeroes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CsGetPlayerHeroes {
    return {};
  },

  toJSON(_: CsGetPlayerHeroes): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CsGetPlayerHeroes>, I>>(base?: I): CsGetPlayerHeroes {
    return CsGetPlayerHeroes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsGetPlayerHeroes>, I>>(_: I): CsGetPlayerHeroes {
    const message = createBaseCsGetPlayerHeroes();
    return message;
  },
};

function createBaseScGetPlayerHeroes(): ScGetPlayerHeroes {
  return { heroInfos: [] };
}

export const ScGetPlayerHeroes: MessageFns<ScGetPlayerHeroes> = {
  encode(message: ScGetPlayerHeroes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.heroInfos) {
      HeroInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScGetPlayerHeroes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScGetPlayerHeroes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.heroInfos.push(HeroInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScGetPlayerHeroes {
    return {
      heroInfos: globalThis.Array.isArray(object?.heroInfos)
        ? object.heroInfos.map((e: any) => HeroInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ScGetPlayerHeroes): unknown {
    const obj: any = {};
    if (message.heroInfos?.length) {
      obj.heroInfos = message.heroInfos.map((e) => HeroInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScGetPlayerHeroes>, I>>(base?: I): ScGetPlayerHeroes {
    return ScGetPlayerHeroes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScGetPlayerHeroes>, I>>(object: I): ScGetPlayerHeroes {
    const message = createBaseScGetPlayerHeroes();
    message.heroInfos = object.heroInfos?.map((e) => HeroInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCsGetPlayerHeroCount(): CsGetPlayerHeroCount {
  return {};
}

export const CsGetPlayerHeroCount: MessageFns<CsGetPlayerHeroCount> = {
  encode(_: CsGetPlayerHeroCount, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsGetPlayerHeroCount {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsGetPlayerHeroCount();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CsGetPlayerHeroCount {
    return {};
  },

  toJSON(_: CsGetPlayerHeroCount): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CsGetPlayerHeroCount>, I>>(base?: I): CsGetPlayerHeroCount {
    return CsGetPlayerHeroCount.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsGetPlayerHeroCount>, I>>(_: I): CsGetPlayerHeroCount {
    const message = createBaseCsGetPlayerHeroCount();
    return message;
  },
};

function createBaseScGetPlayerHeroCount(): ScGetPlayerHeroCount {
  return { heroCount: 0 };
}

export const ScGetPlayerHeroCount: MessageFns<ScGetPlayerHeroCount> = {
  encode(message: ScGetPlayerHeroCount, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.heroCount !== 0) {
      writer.uint32(8).int32(message.heroCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScGetPlayerHeroCount {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScGetPlayerHeroCount();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.heroCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScGetPlayerHeroCount {
    return { heroCount: isSet(object.heroCount) ? globalThis.Number(object.heroCount) : 0 };
  },

  toJSON(message: ScGetPlayerHeroCount): unknown {
    const obj: any = {};
    if (message.heroCount !== 0) {
      obj.heroCount = Math.round(message.heroCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScGetPlayerHeroCount>, I>>(base?: I): ScGetPlayerHeroCount {
    return ScGetPlayerHeroCount.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScGetPlayerHeroCount>, I>>(object: I): ScGetPlayerHeroCount {
    const message = createBaseScGetPlayerHeroCount();
    message.heroCount = object.heroCount ?? 0;
    return message;
  },
};

function createBaseCsActivateHero(): CsActivateHero {
  return { heroTableId: 0 };
}

export const CsActivateHero: MessageFns<CsActivateHero> = {
  encode(message: CsActivateHero, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.heroTableId !== 0) {
      writer.uint32(8).int32(message.heroTableId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsActivateHero {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsActivateHero();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.heroTableId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsActivateHero {
    return { heroTableId: isSet(object.heroTableId) ? globalThis.Number(object.heroTableId) : 0 };
  },

  toJSON(message: CsActivateHero): unknown {
    const obj: any = {};
    if (message.heroTableId !== 0) {
      obj.heroTableId = Math.round(message.heroTableId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsActivateHero>, I>>(base?: I): CsActivateHero {
    return CsActivateHero.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsActivateHero>, I>>(object: I): CsActivateHero {
    const message = createBaseCsActivateHero();
    message.heroTableId = object.heroTableId ?? 0;
    return message;
  },
};

function createBaseScActivateHero(): ScActivateHero {
  return { heroInfo: undefined };
}

export const ScActivateHero: MessageFns<ScActivateHero> = {
  encode(message: ScActivateHero, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.heroInfo !== undefined) {
      HeroInfo.encode(message.heroInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScActivateHero {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScActivateHero();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.heroInfo = HeroInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScActivateHero {
    return { heroInfo: isSet(object.heroInfo) ? HeroInfo.fromJSON(object.heroInfo) : undefined };
  },

  toJSON(message: ScActivateHero): unknown {
    const obj: any = {};
    if (message.heroInfo !== undefined) {
      obj.heroInfo = HeroInfo.toJSON(message.heroInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScActivateHero>, I>>(base?: I): ScActivateHero {
    return ScActivateHero.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScActivateHero>, I>>(object: I): ScActivateHero {
    const message = createBaseScActivateHero();
    message.heroInfo = (object.heroInfo !== undefined && object.heroInfo !== null)
      ? HeroInfo.fromPartial(object.heroInfo)
      : undefined;
    return message;
  },
};

function createBaseCsUpgradeStar(): CsUpgradeStar {
  return { heroTableId: 0 };
}

export const CsUpgradeStar: MessageFns<CsUpgradeStar> = {
  encode(message: CsUpgradeStar, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.heroTableId !== 0) {
      writer.uint32(8).int32(message.heroTableId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsUpgradeStar {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsUpgradeStar();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.heroTableId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsUpgradeStar {
    return { heroTableId: isSet(object.heroTableId) ? globalThis.Number(object.heroTableId) : 0 };
  },

  toJSON(message: CsUpgradeStar): unknown {
    const obj: any = {};
    if (message.heroTableId !== 0) {
      obj.heroTableId = Math.round(message.heroTableId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsUpgradeStar>, I>>(base?: I): CsUpgradeStar {
    return CsUpgradeStar.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsUpgradeStar>, I>>(object: I): CsUpgradeStar {
    const message = createBaseCsUpgradeStar();
    message.heroTableId = object.heroTableId ?? 0;
    return message;
  },
};

function createBaseScUpgradeStar(): ScUpgradeStar {
  return { heroInfo: undefined };
}

export const ScUpgradeStar: MessageFns<ScUpgradeStar> = {
  encode(message: ScUpgradeStar, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.heroInfo !== undefined) {
      HeroInfo.encode(message.heroInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScUpgradeStar {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScUpgradeStar();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.heroInfo = HeroInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScUpgradeStar {
    return { heroInfo: isSet(object.heroInfo) ? HeroInfo.fromJSON(object.heroInfo) : undefined };
  },

  toJSON(message: ScUpgradeStar): unknown {
    const obj: any = {};
    if (message.heroInfo !== undefined) {
      obj.heroInfo = HeroInfo.toJSON(message.heroInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScUpgradeStar>, I>>(base?: I): ScUpgradeStar {
    return ScUpgradeStar.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScUpgradeStar>, I>>(object: I): ScUpgradeStar {
    const message = createBaseScUpgradeStar();
    message.heroInfo = (object.heroInfo !== undefined && object.heroInfo !== null)
      ? HeroInfo.fromPartial(object.heroInfo)
      : undefined;
    return message;
  },
};

function createBaseCsUpgradeLevel(): CsUpgradeLevel {
  return { heroTableId: 0, addLv: 0 };
}

export const CsUpgradeLevel: MessageFns<CsUpgradeLevel> = {
  encode(message: CsUpgradeLevel, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.heroTableId !== 0) {
      writer.uint32(8).int32(message.heroTableId);
    }
    if (message.addLv !== 0) {
      writer.uint32(16).int32(message.addLv);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsUpgradeLevel {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsUpgradeLevel();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.heroTableId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.addLv = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsUpgradeLevel {
    return {
      heroTableId: isSet(object.heroTableId) ? globalThis.Number(object.heroTableId) : 0,
      addLv: isSet(object.addLv) ? globalThis.Number(object.addLv) : 0,
    };
  },

  toJSON(message: CsUpgradeLevel): unknown {
    const obj: any = {};
    if (message.heroTableId !== 0) {
      obj.heroTableId = Math.round(message.heroTableId);
    }
    if (message.addLv !== 0) {
      obj.addLv = Math.round(message.addLv);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsUpgradeLevel>, I>>(base?: I): CsUpgradeLevel {
    return CsUpgradeLevel.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsUpgradeLevel>, I>>(object: I): CsUpgradeLevel {
    const message = createBaseCsUpgradeLevel();
    message.heroTableId = object.heroTableId ?? 0;
    message.addLv = object.addLv ?? 0;
    return message;
  },
};

function createBaseScUpgradeLevel(): ScUpgradeLevel {
  return { heroInfo: undefined };
}

export const ScUpgradeLevel: MessageFns<ScUpgradeLevel> = {
  encode(message: ScUpgradeLevel, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.heroInfo !== undefined) {
      HeroInfo.encode(message.heroInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScUpgradeLevel {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScUpgradeLevel();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.heroInfo = HeroInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScUpgradeLevel {
    return { heroInfo: isSet(object.heroInfo) ? HeroInfo.fromJSON(object.heroInfo) : undefined };
  },

  toJSON(message: ScUpgradeLevel): unknown {
    const obj: any = {};
    if (message.heroInfo !== undefined) {
      obj.heroInfo = HeroInfo.toJSON(message.heroInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScUpgradeLevel>, I>>(base?: I): ScUpgradeLevel {
    return ScUpgradeLevel.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScUpgradeLevel>, I>>(object: I): ScUpgradeLevel {
    const message = createBaseScUpgradeLevel();
    message.heroInfo = (object.heroInfo !== undefined && object.heroInfo !== null)
      ? HeroInfo.fromPartial(object.heroInfo)
      : undefined;
    return message;
  },
};

function createBaseCsUpgradeLevelAuto(): CsUpgradeLevelAuto {
  return { heroTableId: 0 };
}

export const CsUpgradeLevelAuto: MessageFns<CsUpgradeLevelAuto> = {
  encode(message: CsUpgradeLevelAuto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.heroTableId !== 0) {
      writer.uint32(8).int32(message.heroTableId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsUpgradeLevelAuto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsUpgradeLevelAuto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.heroTableId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsUpgradeLevelAuto {
    return { heroTableId: isSet(object.heroTableId) ? globalThis.Number(object.heroTableId) : 0 };
  },

  toJSON(message: CsUpgradeLevelAuto): unknown {
    const obj: any = {};
    if (message.heroTableId !== 0) {
      obj.heroTableId = Math.round(message.heroTableId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsUpgradeLevelAuto>, I>>(base?: I): CsUpgradeLevelAuto {
    return CsUpgradeLevelAuto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsUpgradeLevelAuto>, I>>(object: I): CsUpgradeLevelAuto {
    const message = createBaseCsUpgradeLevelAuto();
    message.heroTableId = object.heroTableId ?? 0;
    return message;
  },
};

function createBaseScUpgradeLevelAuto(): ScUpgradeLevelAuto {
  return { heroInfo: undefined };
}

export const ScUpgradeLevelAuto: MessageFns<ScUpgradeLevelAuto> = {
  encode(message: ScUpgradeLevelAuto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.heroInfo !== undefined) {
      HeroInfo.encode(message.heroInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScUpgradeLevelAuto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScUpgradeLevelAuto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.heroInfo = HeroInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScUpgradeLevelAuto {
    return { heroInfo: isSet(object.heroInfo) ? HeroInfo.fromJSON(object.heroInfo) : undefined };
  },

  toJSON(message: ScUpgradeLevelAuto): unknown {
    const obj: any = {};
    if (message.heroInfo !== undefined) {
      obj.heroInfo = HeroInfo.toJSON(message.heroInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScUpgradeLevelAuto>, I>>(base?: I): ScUpgradeLevelAuto {
    return ScUpgradeLevelAuto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScUpgradeLevelAuto>, I>>(object: I): ScUpgradeLevelAuto {
    const message = createBaseScUpgradeLevelAuto();
    message.heroInfo = (object.heroInfo !== undefined && object.heroInfo !== null)
      ? HeroInfo.fromPartial(object.heroInfo)
      : undefined;
    return message;
  },
};

function createBaseCsActivateTrain(): CsActivateTrain {
  return { heroTableId: 0, trainIndex: 0 };
}

export const CsActivateTrain: MessageFns<CsActivateTrain> = {
  encode(message: CsActivateTrain, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.heroTableId !== 0) {
      writer.uint32(8).int32(message.heroTableId);
    }
    if (message.trainIndex !== 0) {
      writer.uint32(16).int32(message.trainIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsActivateTrain {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsActivateTrain();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.heroTableId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.trainIndex = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsActivateTrain {
    return {
      heroTableId: isSet(object.heroTableId) ? globalThis.Number(object.heroTableId) : 0,
      trainIndex: isSet(object.trainIndex) ? globalThis.Number(object.trainIndex) : 0,
    };
  },

  toJSON(message: CsActivateTrain): unknown {
    const obj: any = {};
    if (message.heroTableId !== 0) {
      obj.heroTableId = Math.round(message.heroTableId);
    }
    if (message.trainIndex !== 0) {
      obj.trainIndex = Math.round(message.trainIndex);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsActivateTrain>, I>>(base?: I): CsActivateTrain {
    return CsActivateTrain.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsActivateTrain>, I>>(object: I): CsActivateTrain {
    const message = createBaseCsActivateTrain();
    message.heroTableId = object.heroTableId ?? 0;
    message.trainIndex = object.trainIndex ?? 0;
    return message;
  },
};

function createBaseScActivateTrain(): ScActivateTrain {
  return { heroInfo: undefined };
}

export const ScActivateTrain: MessageFns<ScActivateTrain> = {
  encode(message: ScActivateTrain, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.heroInfo !== undefined) {
      HeroInfo.encode(message.heroInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScActivateTrain {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScActivateTrain();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.heroInfo = HeroInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScActivateTrain {
    return { heroInfo: isSet(object.heroInfo) ? HeroInfo.fromJSON(object.heroInfo) : undefined };
  },

  toJSON(message: ScActivateTrain): unknown {
    const obj: any = {};
    if (message.heroInfo !== undefined) {
      obj.heroInfo = HeroInfo.toJSON(message.heroInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScActivateTrain>, I>>(base?: I): ScActivateTrain {
    return ScActivateTrain.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScActivateTrain>, I>>(object: I): ScActivateTrain {
    const message = createBaseScActivateTrain();
    message.heroInfo = (object.heroInfo !== undefined && object.heroInfo !== null)
      ? HeroInfo.fromPartial(object.heroInfo)
      : undefined;
    return message;
  },
};

function createBaseCsUpgradeJobRank(): CsUpgradeJobRank {
  return { heroTableId: 0 };
}

export const CsUpgradeJobRank: MessageFns<CsUpgradeJobRank> = {
  encode(message: CsUpgradeJobRank, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.heroTableId !== 0) {
      writer.uint32(8).int32(message.heroTableId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsUpgradeJobRank {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsUpgradeJobRank();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.heroTableId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsUpgradeJobRank {
    return { heroTableId: isSet(object.heroTableId) ? globalThis.Number(object.heroTableId) : 0 };
  },

  toJSON(message: CsUpgradeJobRank): unknown {
    const obj: any = {};
    if (message.heroTableId !== 0) {
      obj.heroTableId = Math.round(message.heroTableId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsUpgradeJobRank>, I>>(base?: I): CsUpgradeJobRank {
    return CsUpgradeJobRank.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsUpgradeJobRank>, I>>(object: I): CsUpgradeJobRank {
    const message = createBaseCsUpgradeJobRank();
    message.heroTableId = object.heroTableId ?? 0;
    return message;
  },
};

function createBaseScUpgradeJobRank(): ScUpgradeJobRank {
  return { heroInfo: undefined };
}

export const ScUpgradeJobRank: MessageFns<ScUpgradeJobRank> = {
  encode(message: ScUpgradeJobRank, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.heroInfo !== undefined) {
      HeroInfo.encode(message.heroInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScUpgradeJobRank {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScUpgradeJobRank();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.heroInfo = HeroInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScUpgradeJobRank {
    return { heroInfo: isSet(object.heroInfo) ? HeroInfo.fromJSON(object.heroInfo) : undefined };
  },

  toJSON(message: ScUpgradeJobRank): unknown {
    const obj: any = {};
    if (message.heroInfo !== undefined) {
      obj.heroInfo = HeroInfo.toJSON(message.heroInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScUpgradeJobRank>, I>>(base?: I): ScUpgradeJobRank {
    return ScUpgradeJobRank.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScUpgradeJobRank>, I>>(object: I): ScUpgradeJobRank {
    const message = createBaseScUpgradeJobRank();
    message.heroInfo = (object.heroInfo !== undefined && object.heroInfo !== null)
      ? HeroInfo.fromPartial(object.heroInfo)
      : undefined;
    return message;
  },
};

function createBaseCsUpgradeSkill(): CsUpgradeSkill {
  return { heroTableId: 0, skillIndex: 0 };
}

export const CsUpgradeSkill: MessageFns<CsUpgradeSkill> = {
  encode(message: CsUpgradeSkill, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.heroTableId !== 0) {
      writer.uint32(8).int32(message.heroTableId);
    }
    if (message.skillIndex !== 0) {
      writer.uint32(16).int32(message.skillIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsUpgradeSkill {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsUpgradeSkill();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.heroTableId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.skillIndex = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsUpgradeSkill {
    return {
      heroTableId: isSet(object.heroTableId) ? globalThis.Number(object.heroTableId) : 0,
      skillIndex: isSet(object.skillIndex) ? globalThis.Number(object.skillIndex) : 0,
    };
  },

  toJSON(message: CsUpgradeSkill): unknown {
    const obj: any = {};
    if (message.heroTableId !== 0) {
      obj.heroTableId = Math.round(message.heroTableId);
    }
    if (message.skillIndex !== 0) {
      obj.skillIndex = Math.round(message.skillIndex);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsUpgradeSkill>, I>>(base?: I): CsUpgradeSkill {
    return CsUpgradeSkill.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsUpgradeSkill>, I>>(object: I): CsUpgradeSkill {
    const message = createBaseCsUpgradeSkill();
    message.heroTableId = object.heroTableId ?? 0;
    message.skillIndex = object.skillIndex ?? 0;
    return message;
  },
};

function createBaseScUpgradeSkill(): ScUpgradeSkill {
  return { heroInfo: undefined };
}

export const ScUpgradeSkill: MessageFns<ScUpgradeSkill> = {
  encode(message: ScUpgradeSkill, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.heroInfo !== undefined) {
      HeroInfo.encode(message.heroInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScUpgradeSkill {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScUpgradeSkill();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.heroInfo = HeroInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScUpgradeSkill {
    return { heroInfo: isSet(object.heroInfo) ? HeroInfo.fromJSON(object.heroInfo) : undefined };
  },

  toJSON(message: ScUpgradeSkill): unknown {
    const obj: any = {};
    if (message.heroInfo !== undefined) {
      obj.heroInfo = HeroInfo.toJSON(message.heroInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScUpgradeSkill>, I>>(base?: I): ScUpgradeSkill {
    return ScUpgradeSkill.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScUpgradeSkill>, I>>(object: I): ScUpgradeSkill {
    const message = createBaseScUpgradeSkill();
    message.heroInfo = (object.heroInfo !== undefined && object.heroInfo !== null)
      ? HeroInfo.fromPartial(object.heroInfo)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}

export const csGetHeroId: number = 1001;
export const scGetHeroId: number = 1002;
export const csGetPlayerHeroesId: number = 1003;
export const scGetPlayerHeroesId: number = 1004;
export const csGetPlayerHeroCountId: number = 1005;
export const scGetPlayerHeroCountId: number = 1006;
export const csActivateHeroId: number = 1007;
export const scActivateHeroId: number = 1008;
export const csUpgradeStarId: number = 1009;
export const scUpgradeStarId: number = 1010;
export const csUpgradeLevelId: number = 1011;
export const scUpgradeLevelId: number = 1012;
export const csUpgradeLevelAutoId: number = 1013;
export const scUpgradeLevelAutoId: number = 1014;
export const csActivateTrainId: number = 1015;
export const scActivateTrainId: number = 1016;
export const csUpgradeJobRankId: number = 1017;
export const scUpgradeJobRankId: number = 1018;
export const csUpgradeSkillId: number = 1019;
export const scUpgradeSkillId: number = 1020;
