// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.33.5
// source: MessagePlayer.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

/** 0-1000 */
export interface PlayerInfo {
  playerId: string;
  playerName: string;
  lv: number;
  vipLv: number;
  /** 元宝 */
  ingot: number;
  /** 铜币 */
  copperCoin: number;
  /** 粮草 */
  provisions: number;
  /** 功勋 */
  exploit: number;
  /** 军团 */
  legionId: string;
  /** 世界等级 */
  worldLv: number;
}

/**
 * 登录信息
 * @Id(100)
 */
export interface CsPlayerLogin {
  username: string;
  toke: string;
  pfStr: string;
  serverId: number;
}

/**
 * 登录信息
 * @Id(101)
 */
export interface ScPlayerLogin {
  playerInfo?: PlayerInfo | undefined;
}

function createBasePlayerInfo(): PlayerInfo {
  return {
    playerId: "",
    playerName: "",
    lv: 0,
    vipLv: 0,
    ingot: 0,
    copperCoin: 0,
    provisions: 0,
    exploit: 0,
    legionId: "",
    worldLv: 0,
  };
}

export const PlayerInfo: MessageFns<PlayerInfo> = {
  encode(message: PlayerInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.playerId !== "") {
      writer.uint32(10).string(message.playerId);
    }
    if (message.playerName !== "") {
      writer.uint32(18).string(message.playerName);
    }
    if (message.lv !== 0) {
      writer.uint32(24).int32(message.lv);
    }
    if (message.vipLv !== 0) {
      writer.uint32(32).int32(message.vipLv);
    }
    if (message.ingot !== 0) {
      writer.uint32(40).int32(message.ingot);
    }
    if (message.copperCoin !== 0) {
      writer.uint32(48).int32(message.copperCoin);
    }
    if (message.provisions !== 0) {
      writer.uint32(56).int32(message.provisions);
    }
    if (message.exploit !== 0) {
      writer.uint32(64).int32(message.exploit);
    }
    if (message.legionId !== "") {
      writer.uint32(74).string(message.legionId);
    }
    if (message.worldLv !== 0) {
      writer.uint32(80).int32(message.worldLv);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PlayerInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlayerInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.playerId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.playerName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.lv = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.vipLv = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.ingot = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.copperCoin = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.provisions = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.exploit = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.legionId = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.worldLv = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PlayerInfo {
    return {
      playerId: isSet(object.playerId) ? globalThis.String(object.playerId) : "",
      playerName: isSet(object.playerName) ? globalThis.String(object.playerName) : "",
      lv: isSet(object.lv) ? globalThis.Number(object.lv) : 0,
      vipLv: isSet(object.vipLv) ? globalThis.Number(object.vipLv) : 0,
      ingot: isSet(object.ingot) ? globalThis.Number(object.ingot) : 0,
      copperCoin: isSet(object.copperCoin) ? globalThis.Number(object.copperCoin) : 0,
      provisions: isSet(object.provisions) ? globalThis.Number(object.provisions) : 0,
      exploit: isSet(object.exploit) ? globalThis.Number(object.exploit) : 0,
      legionId: isSet(object.legionId) ? globalThis.String(object.legionId) : "",
      worldLv: isSet(object.worldLv) ? globalThis.Number(object.worldLv) : 0,
    };
  },

  toJSON(message: PlayerInfo): unknown {
    const obj: any = {};
    if (message.playerId !== "") {
      obj.playerId = message.playerId;
    }
    if (message.playerName !== "") {
      obj.playerName = message.playerName;
    }
    if (message.lv !== 0) {
      obj.lv = Math.round(message.lv);
    }
    if (message.vipLv !== 0) {
      obj.vipLv = Math.round(message.vipLv);
    }
    if (message.ingot !== 0) {
      obj.ingot = Math.round(message.ingot);
    }
    if (message.copperCoin !== 0) {
      obj.copperCoin = Math.round(message.copperCoin);
    }
    if (message.provisions !== 0) {
      obj.provisions = Math.round(message.provisions);
    }
    if (message.exploit !== 0) {
      obj.exploit = Math.round(message.exploit);
    }
    if (message.legionId !== "") {
      obj.legionId = message.legionId;
    }
    if (message.worldLv !== 0) {
      obj.worldLv = Math.round(message.worldLv);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PlayerInfo>, I>>(base?: I): PlayerInfo {
    return PlayerInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PlayerInfo>, I>>(object: I): PlayerInfo {
    const message = createBasePlayerInfo();
    message.playerId = object.playerId ?? "";
    message.playerName = object.playerName ?? "";
    message.lv = object.lv ?? 0;
    message.vipLv = object.vipLv ?? 0;
    message.ingot = object.ingot ?? 0;
    message.copperCoin = object.copperCoin ?? 0;
    message.provisions = object.provisions ?? 0;
    message.exploit = object.exploit ?? 0;
    message.legionId = object.legionId ?? "";
    message.worldLv = object.worldLv ?? 0;
    return message;
  },
};

function createBaseCsPlayerLogin(): CsPlayerLogin {
  return { username: "", toke: "", pfStr: "", serverId: 0 };
}

export const CsPlayerLogin: MessageFns<CsPlayerLogin> = {
  encode(message: CsPlayerLogin, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.toke !== "") {
      writer.uint32(18).string(message.toke);
    }
    if (message.pfStr !== "") {
      writer.uint32(26).string(message.pfStr);
    }
    if (message.serverId !== 0) {
      writer.uint32(32).int32(message.serverId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsPlayerLogin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsPlayerLogin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.toke = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pfStr = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.serverId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsPlayerLogin {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      toke: isSet(object.toke) ? globalThis.String(object.toke) : "",
      pfStr: isSet(object.pfStr) ? globalThis.String(object.pfStr) : "",
      serverId: isSet(object.serverId) ? globalThis.Number(object.serverId) : 0,
    };
  },

  toJSON(message: CsPlayerLogin): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.toke !== "") {
      obj.toke = message.toke;
    }
    if (message.pfStr !== "") {
      obj.pfStr = message.pfStr;
    }
    if (message.serverId !== 0) {
      obj.serverId = Math.round(message.serverId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsPlayerLogin>, I>>(base?: I): CsPlayerLogin {
    return CsPlayerLogin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsPlayerLogin>, I>>(object: I): CsPlayerLogin {
    const message = createBaseCsPlayerLogin();
    message.username = object.username ?? "";
    message.toke = object.toke ?? "";
    message.pfStr = object.pfStr ?? "";
    message.serverId = object.serverId ?? 0;
    return message;
  },
};

function createBaseScPlayerLogin(): ScPlayerLogin {
  return { playerInfo: undefined };
}

export const ScPlayerLogin: MessageFns<ScPlayerLogin> = {
  encode(message: ScPlayerLogin, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.playerInfo !== undefined) {
      PlayerInfo.encode(message.playerInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScPlayerLogin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScPlayerLogin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.playerInfo = PlayerInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScPlayerLogin {
    return { playerInfo: isSet(object.playerInfo) ? PlayerInfo.fromJSON(object.playerInfo) : undefined };
  },

  toJSON(message: ScPlayerLogin): unknown {
    const obj: any = {};
    if (message.playerInfo !== undefined) {
      obj.playerInfo = PlayerInfo.toJSON(message.playerInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScPlayerLogin>, I>>(base?: I): ScPlayerLogin {
    return ScPlayerLogin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScPlayerLogin>, I>>(object: I): ScPlayerLogin {
    const message = createBaseScPlayerLogin();
    message.playerInfo = (object.playerInfo !== undefined && object.playerInfo !== null)
      ? PlayerInfo.fromPartial(object.playerInfo)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}

export const csPlayerLoginId: number = 100;
export const scPlayerLoginId: number = 101;
