// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.33.5
// source: structure.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "protobuf";

export interface HeroInfo {
  heroTableId: number;
  star: number;
  lv: number;
  /** 兵种等级 */
  rank: number;
  train1: boolean;
  train2: boolean;
  train3: boolean;
  train4: boolean;
  skillInfo: HeroSkillInfo[];
  power: string;
  attributes: Attribute[];
  dispatchToCityId: number;
}

export interface Attribute {
  attrKey: number;
  attrValue: string;
}

export interface HeroSkillInfo {
  skillId: number;
  skillLv: number;
}

export interface ItemInfo {
  id: string;
  tableId: number;
  itemCount: number;
}

export interface LegionBaseInfo {
  legionId: string;
  name: string;
  banner: string;
  flagId: number;
}

export interface LegionListInfo {
  legionId: string;
  name: string;
  banner: string;
  flagId: number;
  level: number;
  notice: string;
  joinCondition: number;
  joinPowerReq: string;
  joinLevelReq: number;
  application: boolean;
}

export interface LegionInfo {
  legionId: string;
  name: string;
  banner: string;
  flagId: number;
  leaderId: string;
  level: number;
  militaryFund: string;
  notice: string;
  joinCondition: number;
  joinPowerReq: string;
  joinLevelReq: number;
  createTime: string;
  transferCooldown: string;
}

export interface LegionMemberInfo {
  playerId: string;
  legionId: string;
  position: number;
  joinTime: string;
  todayContribution: number;
  totalContribution: number;
  quitTime: string;
}

export interface LegionDetailInfo {
  legionInfo?: LegionInfo | undefined;
  legionMemberInfos: LegionMemberInfo[];
}

export interface CityInfo {
  cityId: number;
  ownerLegionInfo?: LegionBaseInfo | undefined;
  cityStatus: number;
  garrisonCurrentCount: number;
  lastAddGarrisonTime: string;
  declaringLegionInfo?: LegionBaseInfo | undefined;
  statusChangeTime: string;
  isUnlock: boolean;
  battleInfo: BattleInfo[];
  battleRemainingTime: number;
}

export interface BattleInfo {
  battleIndex: number;
  attack?: BattleUnit | undefined;
  defend?: BattleUnit | undefined;
}

export interface HeroState {
  heroId: number;
  maxHp: string;
  currentHp: string;
  debuffStacks: number;
  garrisonType: number;
}

export interface BattleUnit {
  hero: HeroState[];
  playerId: string;
  playerName: string;
  legionId: string;
  legionName: string;
  totalPower: string;
  isGarrison: boolean;
  dispatchId: string;
}

export interface CityBattleDetail {
  battleInfo: BattleInfo[];
  attackQueue: BattleUnit[];
  defendQueue: BattleUnit[];
  garrisonQueue: BattleUnit[];
  battleRemainingTime: number;
  cityId: number;
}

function createBaseHeroInfo(): HeroInfo {
  return {
    heroTableId: 0,
    star: 0,
    lv: 0,
    rank: 0,
    train1: false,
    train2: false,
    train3: false,
    train4: false,
    skillInfo: [],
    power: "",
    attributes: [],
    dispatchToCityId: 0,
  };
}

export const HeroInfo: MessageFns<HeroInfo> = {
  encode(message: HeroInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.heroTableId !== 0) {
      writer.uint32(8).int32(message.heroTableId);
    }
    if (message.star !== 0) {
      writer.uint32(16).int32(message.star);
    }
    if (message.lv !== 0) {
      writer.uint32(24).int32(message.lv);
    }
    if (message.rank !== 0) {
      writer.uint32(32).int32(message.rank);
    }
    if (message.train1 !== false) {
      writer.uint32(40).bool(message.train1);
    }
    if (message.train2 !== false) {
      writer.uint32(48).bool(message.train2);
    }
    if (message.train3 !== false) {
      writer.uint32(56).bool(message.train3);
    }
    if (message.train4 !== false) {
      writer.uint32(64).bool(message.train4);
    }
    for (const v of message.skillInfo) {
      HeroSkillInfo.encode(v!, writer.uint32(74).fork()).join();
    }
    if (message.power !== "") {
      writer.uint32(82).string(message.power);
    }
    for (const v of message.attributes) {
      Attribute.encode(v!, writer.uint32(90).fork()).join();
    }
    if (message.dispatchToCityId !== 0) {
      writer.uint32(96).int32(message.dispatchToCityId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HeroInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeroInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.heroTableId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.star = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.lv = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.rank = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.train1 = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.train2 = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.train3 = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.train4 = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.skillInfo.push(HeroSkillInfo.decode(reader, reader.uint32()));
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.power = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.attributes.push(Attribute.decode(reader, reader.uint32()));
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.dispatchToCityId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HeroInfo {
    return {
      heroTableId: isSet(object.heroTableId) ? globalThis.Number(object.heroTableId) : 0,
      star: isSet(object.star) ? globalThis.Number(object.star) : 0,
      lv: isSet(object.lv) ? globalThis.Number(object.lv) : 0,
      rank: isSet(object.rank) ? globalThis.Number(object.rank) : 0,
      train1: isSet(object.train1) ? globalThis.Boolean(object.train1) : false,
      train2: isSet(object.train2) ? globalThis.Boolean(object.train2) : false,
      train3: isSet(object.train3) ? globalThis.Boolean(object.train3) : false,
      train4: isSet(object.train4) ? globalThis.Boolean(object.train4) : false,
      skillInfo: globalThis.Array.isArray(object?.skillInfo)
        ? object.skillInfo.map((e: any) => HeroSkillInfo.fromJSON(e))
        : [],
      power: isSet(object.power) ? globalThis.String(object.power) : "",
      attributes: globalThis.Array.isArray(object?.attributes)
        ? object.attributes.map((e: any) => Attribute.fromJSON(e))
        : [],
      dispatchToCityId: isSet(object.dispatchToCityId) ? globalThis.Number(object.dispatchToCityId) : 0,
    };
  },

  toJSON(message: HeroInfo): unknown {
    const obj: any = {};
    if (message.heroTableId !== 0) {
      obj.heroTableId = Math.round(message.heroTableId);
    }
    if (message.star !== 0) {
      obj.star = Math.round(message.star);
    }
    if (message.lv !== 0) {
      obj.lv = Math.round(message.lv);
    }
    if (message.rank !== 0) {
      obj.rank = Math.round(message.rank);
    }
    if (message.train1 !== false) {
      obj.train1 = message.train1;
    }
    if (message.train2 !== false) {
      obj.train2 = message.train2;
    }
    if (message.train3 !== false) {
      obj.train3 = message.train3;
    }
    if (message.train4 !== false) {
      obj.train4 = message.train4;
    }
    if (message.skillInfo?.length) {
      obj.skillInfo = message.skillInfo.map((e) => HeroSkillInfo.toJSON(e));
    }
    if (message.power !== "") {
      obj.power = message.power;
    }
    if (message.attributes?.length) {
      obj.attributes = message.attributes.map((e) => Attribute.toJSON(e));
    }
    if (message.dispatchToCityId !== 0) {
      obj.dispatchToCityId = Math.round(message.dispatchToCityId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HeroInfo>, I>>(base?: I): HeroInfo {
    return HeroInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HeroInfo>, I>>(object: I): HeroInfo {
    const message = createBaseHeroInfo();
    message.heroTableId = object.heroTableId ?? 0;
    message.star = object.star ?? 0;
    message.lv = object.lv ?? 0;
    message.rank = object.rank ?? 0;
    message.train1 = object.train1 ?? false;
    message.train2 = object.train2 ?? false;
    message.train3 = object.train3 ?? false;
    message.train4 = object.train4 ?? false;
    message.skillInfo = object.skillInfo?.map((e) => HeroSkillInfo.fromPartial(e)) || [];
    message.power = object.power ?? "";
    message.attributes = object.attributes?.map((e) => Attribute.fromPartial(e)) || [];
    message.dispatchToCityId = object.dispatchToCityId ?? 0;
    return message;
  },
};

function createBaseAttribute(): Attribute {
  return { attrKey: 0, attrValue: "" };
}

export const Attribute: MessageFns<Attribute> = {
  encode(message: Attribute, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.attrKey !== 0) {
      writer.uint32(8).int32(message.attrKey);
    }
    if (message.attrValue !== "") {
      writer.uint32(18).string(message.attrValue);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Attribute {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAttribute();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.attrKey = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.attrValue = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Attribute {
    return {
      attrKey: isSet(object.attrKey) ? globalThis.Number(object.attrKey) : 0,
      attrValue: isSet(object.attrValue) ? globalThis.String(object.attrValue) : "",
    };
  },

  toJSON(message: Attribute): unknown {
    const obj: any = {};
    if (message.attrKey !== 0) {
      obj.attrKey = Math.round(message.attrKey);
    }
    if (message.attrValue !== "") {
      obj.attrValue = message.attrValue;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Attribute>, I>>(base?: I): Attribute {
    return Attribute.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Attribute>, I>>(object: I): Attribute {
    const message = createBaseAttribute();
    message.attrKey = object.attrKey ?? 0;
    message.attrValue = object.attrValue ?? "";
    return message;
  },
};

function createBaseHeroSkillInfo(): HeroSkillInfo {
  return { skillId: 0, skillLv: 0 };
}

export const HeroSkillInfo: MessageFns<HeroSkillInfo> = {
  encode(message: HeroSkillInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.skillId !== 0) {
      writer.uint32(8).int32(message.skillId);
    }
    if (message.skillLv !== 0) {
      writer.uint32(16).int32(message.skillLv);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HeroSkillInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeroSkillInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.skillId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.skillLv = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HeroSkillInfo {
    return {
      skillId: isSet(object.skillId) ? globalThis.Number(object.skillId) : 0,
      skillLv: isSet(object.skillLv) ? globalThis.Number(object.skillLv) : 0,
    };
  },

  toJSON(message: HeroSkillInfo): unknown {
    const obj: any = {};
    if (message.skillId !== 0) {
      obj.skillId = Math.round(message.skillId);
    }
    if (message.skillLv !== 0) {
      obj.skillLv = Math.round(message.skillLv);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HeroSkillInfo>, I>>(base?: I): HeroSkillInfo {
    return HeroSkillInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HeroSkillInfo>, I>>(object: I): HeroSkillInfo {
    const message = createBaseHeroSkillInfo();
    message.skillId = object.skillId ?? 0;
    message.skillLv = object.skillLv ?? 0;
    return message;
  },
};

function createBaseItemInfo(): ItemInfo {
  return { id: "", tableId: 0, itemCount: 0 };
}

export const ItemInfo: MessageFns<ItemInfo> = {
  encode(message: ItemInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.tableId !== 0) {
      writer.uint32(16).int32(message.tableId);
    }
    if (message.itemCount !== 0) {
      writer.uint32(24).int32(message.itemCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ItemInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItemInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.tableId = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.itemCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ItemInfo {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      tableId: isSet(object.tableId) ? globalThis.Number(object.tableId) : 0,
      itemCount: isSet(object.itemCount) ? globalThis.Number(object.itemCount) : 0,
    };
  },

  toJSON(message: ItemInfo): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.tableId !== 0) {
      obj.tableId = Math.round(message.tableId);
    }
    if (message.itemCount !== 0) {
      obj.itemCount = Math.round(message.itemCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ItemInfo>, I>>(base?: I): ItemInfo {
    return ItemInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ItemInfo>, I>>(object: I): ItemInfo {
    const message = createBaseItemInfo();
    message.id = object.id ?? "";
    message.tableId = object.tableId ?? 0;
    message.itemCount = object.itemCount ?? 0;
    return message;
  },
};

function createBaseLegionBaseInfo(): LegionBaseInfo {
  return { legionId: "", name: "", banner: "", flagId: 0 };
}

export const LegionBaseInfo: MessageFns<LegionBaseInfo> = {
  encode(message: LegionBaseInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionId !== "") {
      writer.uint32(10).string(message.legionId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.banner !== "") {
      writer.uint32(26).string(message.banner);
    }
    if (message.flagId !== 0) {
      writer.uint32(32).int32(message.flagId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LegionBaseInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLegionBaseInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.banner = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.flagId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LegionBaseInfo {
    return {
      legionId: isSet(object.legionId) ? globalThis.String(object.legionId) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      banner: isSet(object.banner) ? globalThis.String(object.banner) : "",
      flagId: isSet(object.flagId) ? globalThis.Number(object.flagId) : 0,
    };
  },

  toJSON(message: LegionBaseInfo): unknown {
    const obj: any = {};
    if (message.legionId !== "") {
      obj.legionId = message.legionId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.banner !== "") {
      obj.banner = message.banner;
    }
    if (message.flagId !== 0) {
      obj.flagId = Math.round(message.flagId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LegionBaseInfo>, I>>(base?: I): LegionBaseInfo {
    return LegionBaseInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LegionBaseInfo>, I>>(object: I): LegionBaseInfo {
    const message = createBaseLegionBaseInfo();
    message.legionId = object.legionId ?? "";
    message.name = object.name ?? "";
    message.banner = object.banner ?? "";
    message.flagId = object.flagId ?? 0;
    return message;
  },
};

function createBaseLegionListInfo(): LegionListInfo {
  return {
    legionId: "",
    name: "",
    banner: "",
    flagId: 0,
    level: 0,
    notice: "",
    joinCondition: 0,
    joinPowerReq: "",
    joinLevelReq: 0,
    application: false,
  };
}

export const LegionListInfo: MessageFns<LegionListInfo> = {
  encode(message: LegionListInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionId !== "") {
      writer.uint32(10).string(message.legionId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.banner !== "") {
      writer.uint32(26).string(message.banner);
    }
    if (message.flagId !== 0) {
      writer.uint32(32).int32(message.flagId);
    }
    if (message.level !== 0) {
      writer.uint32(40).int32(message.level);
    }
    if (message.notice !== "") {
      writer.uint32(50).string(message.notice);
    }
    if (message.joinCondition !== 0) {
      writer.uint32(56).int32(message.joinCondition);
    }
    if (message.joinPowerReq !== "") {
      writer.uint32(66).string(message.joinPowerReq);
    }
    if (message.joinLevelReq !== 0) {
      writer.uint32(72).int32(message.joinLevelReq);
    }
    if (message.application !== false) {
      writer.uint32(80).bool(message.application);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LegionListInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLegionListInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.banner = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.flagId = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.level = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.notice = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.joinCondition = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.joinPowerReq = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.joinLevelReq = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.application = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LegionListInfo {
    return {
      legionId: isSet(object.legionId) ? globalThis.String(object.legionId) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      banner: isSet(object.banner) ? globalThis.String(object.banner) : "",
      flagId: isSet(object.flagId) ? globalThis.Number(object.flagId) : 0,
      level: isSet(object.level) ? globalThis.Number(object.level) : 0,
      notice: isSet(object.notice) ? globalThis.String(object.notice) : "",
      joinCondition: isSet(object.joinCondition) ? globalThis.Number(object.joinCondition) : 0,
      joinPowerReq: isSet(object.joinPowerReq) ? globalThis.String(object.joinPowerReq) : "",
      joinLevelReq: isSet(object.joinLevelReq) ? globalThis.Number(object.joinLevelReq) : 0,
      application: isSet(object.application) ? globalThis.Boolean(object.application) : false,
    };
  },

  toJSON(message: LegionListInfo): unknown {
    const obj: any = {};
    if (message.legionId !== "") {
      obj.legionId = message.legionId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.banner !== "") {
      obj.banner = message.banner;
    }
    if (message.flagId !== 0) {
      obj.flagId = Math.round(message.flagId);
    }
    if (message.level !== 0) {
      obj.level = Math.round(message.level);
    }
    if (message.notice !== "") {
      obj.notice = message.notice;
    }
    if (message.joinCondition !== 0) {
      obj.joinCondition = Math.round(message.joinCondition);
    }
    if (message.joinPowerReq !== "") {
      obj.joinPowerReq = message.joinPowerReq;
    }
    if (message.joinLevelReq !== 0) {
      obj.joinLevelReq = Math.round(message.joinLevelReq);
    }
    if (message.application !== false) {
      obj.application = message.application;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LegionListInfo>, I>>(base?: I): LegionListInfo {
    return LegionListInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LegionListInfo>, I>>(object: I): LegionListInfo {
    const message = createBaseLegionListInfo();
    message.legionId = object.legionId ?? "";
    message.name = object.name ?? "";
    message.banner = object.banner ?? "";
    message.flagId = object.flagId ?? 0;
    message.level = object.level ?? 0;
    message.notice = object.notice ?? "";
    message.joinCondition = object.joinCondition ?? 0;
    message.joinPowerReq = object.joinPowerReq ?? "";
    message.joinLevelReq = object.joinLevelReq ?? 0;
    message.application = object.application ?? false;
    return message;
  },
};

function createBaseLegionInfo(): LegionInfo {
  return {
    legionId: "",
    name: "",
    banner: "",
    flagId: 0,
    leaderId: "",
    level: 0,
    militaryFund: "",
    notice: "",
    joinCondition: 0,
    joinPowerReq: "",
    joinLevelReq: 0,
    createTime: "",
    transferCooldown: "",
  };
}

export const LegionInfo: MessageFns<LegionInfo> = {
  encode(message: LegionInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionId !== "") {
      writer.uint32(10).string(message.legionId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.banner !== "") {
      writer.uint32(26).string(message.banner);
    }
    if (message.flagId !== 0) {
      writer.uint32(32).int32(message.flagId);
    }
    if (message.leaderId !== "") {
      writer.uint32(42).string(message.leaderId);
    }
    if (message.level !== 0) {
      writer.uint32(48).int32(message.level);
    }
    if (message.militaryFund !== "") {
      writer.uint32(58).string(message.militaryFund);
    }
    if (message.notice !== "") {
      writer.uint32(66).string(message.notice);
    }
    if (message.joinCondition !== 0) {
      writer.uint32(72).int32(message.joinCondition);
    }
    if (message.joinPowerReq !== "") {
      writer.uint32(82).string(message.joinPowerReq);
    }
    if (message.joinLevelReq !== 0) {
      writer.uint32(88).int32(message.joinLevelReq);
    }
    if (message.createTime !== "") {
      writer.uint32(98).string(message.createTime);
    }
    if (message.transferCooldown !== "") {
      writer.uint32(106).string(message.transferCooldown);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LegionInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLegionInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.banner = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.flagId = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.leaderId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.level = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.militaryFund = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.notice = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.joinCondition = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.joinPowerReq = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.joinLevelReq = reader.int32();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.createTime = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.transferCooldown = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LegionInfo {
    return {
      legionId: isSet(object.legionId) ? globalThis.String(object.legionId) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      banner: isSet(object.banner) ? globalThis.String(object.banner) : "",
      flagId: isSet(object.flagId) ? globalThis.Number(object.flagId) : 0,
      leaderId: isSet(object.leaderId) ? globalThis.String(object.leaderId) : "",
      level: isSet(object.level) ? globalThis.Number(object.level) : 0,
      militaryFund: isSet(object.militaryFund) ? globalThis.String(object.militaryFund) : "",
      notice: isSet(object.notice) ? globalThis.String(object.notice) : "",
      joinCondition: isSet(object.joinCondition) ? globalThis.Number(object.joinCondition) : 0,
      joinPowerReq: isSet(object.joinPowerReq) ? globalThis.String(object.joinPowerReq) : "",
      joinLevelReq: isSet(object.joinLevelReq) ? globalThis.Number(object.joinLevelReq) : 0,
      createTime: isSet(object.createTime) ? globalThis.String(object.createTime) : "",
      transferCooldown: isSet(object.transferCooldown) ? globalThis.String(object.transferCooldown) : "",
    };
  },

  toJSON(message: LegionInfo): unknown {
    const obj: any = {};
    if (message.legionId !== "") {
      obj.legionId = message.legionId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.banner !== "") {
      obj.banner = message.banner;
    }
    if (message.flagId !== 0) {
      obj.flagId = Math.round(message.flagId);
    }
    if (message.leaderId !== "") {
      obj.leaderId = message.leaderId;
    }
    if (message.level !== 0) {
      obj.level = Math.round(message.level);
    }
    if (message.militaryFund !== "") {
      obj.militaryFund = message.militaryFund;
    }
    if (message.notice !== "") {
      obj.notice = message.notice;
    }
    if (message.joinCondition !== 0) {
      obj.joinCondition = Math.round(message.joinCondition);
    }
    if (message.joinPowerReq !== "") {
      obj.joinPowerReq = message.joinPowerReq;
    }
    if (message.joinLevelReq !== 0) {
      obj.joinLevelReq = Math.round(message.joinLevelReq);
    }
    if (message.createTime !== "") {
      obj.createTime = message.createTime;
    }
    if (message.transferCooldown !== "") {
      obj.transferCooldown = message.transferCooldown;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LegionInfo>, I>>(base?: I): LegionInfo {
    return LegionInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LegionInfo>, I>>(object: I): LegionInfo {
    const message = createBaseLegionInfo();
    message.legionId = object.legionId ?? "";
    message.name = object.name ?? "";
    message.banner = object.banner ?? "";
    message.flagId = object.flagId ?? 0;
    message.leaderId = object.leaderId ?? "";
    message.level = object.level ?? 0;
    message.militaryFund = object.militaryFund ?? "";
    message.notice = object.notice ?? "";
    message.joinCondition = object.joinCondition ?? 0;
    message.joinPowerReq = object.joinPowerReq ?? "";
    message.joinLevelReq = object.joinLevelReq ?? 0;
    message.createTime = object.createTime ?? "";
    message.transferCooldown = object.transferCooldown ?? "";
    return message;
  },
};

function createBaseLegionMemberInfo(): LegionMemberInfo {
  return {
    playerId: "",
    legionId: "",
    position: 0,
    joinTime: "",
    todayContribution: 0,
    totalContribution: 0,
    quitTime: "",
  };
}

export const LegionMemberInfo: MessageFns<LegionMemberInfo> = {
  encode(message: LegionMemberInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.playerId !== "") {
      writer.uint32(10).string(message.playerId);
    }
    if (message.legionId !== "") {
      writer.uint32(18).string(message.legionId);
    }
    if (message.position !== 0) {
      writer.uint32(24).int32(message.position);
    }
    if (message.joinTime !== "") {
      writer.uint32(34).string(message.joinTime);
    }
    if (message.todayContribution !== 0) {
      writer.uint32(40).int32(message.todayContribution);
    }
    if (message.totalContribution !== 0) {
      writer.uint32(48).int32(message.totalContribution);
    }
    if (message.quitTime !== "") {
      writer.uint32(58).string(message.quitTime);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LegionMemberInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLegionMemberInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.playerId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.legionId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.position = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.joinTime = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.todayContribution = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.totalContribution = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.quitTime = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LegionMemberInfo {
    return {
      playerId: isSet(object.playerId) ? globalThis.String(object.playerId) : "",
      legionId: isSet(object.legionId) ? globalThis.String(object.legionId) : "",
      position: isSet(object.position) ? globalThis.Number(object.position) : 0,
      joinTime: isSet(object.joinTime) ? globalThis.String(object.joinTime) : "",
      todayContribution: isSet(object.todayContribution) ? globalThis.Number(object.todayContribution) : 0,
      totalContribution: isSet(object.totalContribution) ? globalThis.Number(object.totalContribution) : 0,
      quitTime: isSet(object.quitTime) ? globalThis.String(object.quitTime) : "",
    };
  },

  toJSON(message: LegionMemberInfo): unknown {
    const obj: any = {};
    if (message.playerId !== "") {
      obj.playerId = message.playerId;
    }
    if (message.legionId !== "") {
      obj.legionId = message.legionId;
    }
    if (message.position !== 0) {
      obj.position = Math.round(message.position);
    }
    if (message.joinTime !== "") {
      obj.joinTime = message.joinTime;
    }
    if (message.todayContribution !== 0) {
      obj.todayContribution = Math.round(message.todayContribution);
    }
    if (message.totalContribution !== 0) {
      obj.totalContribution = Math.round(message.totalContribution);
    }
    if (message.quitTime !== "") {
      obj.quitTime = message.quitTime;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LegionMemberInfo>, I>>(base?: I): LegionMemberInfo {
    return LegionMemberInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LegionMemberInfo>, I>>(object: I): LegionMemberInfo {
    const message = createBaseLegionMemberInfo();
    message.playerId = object.playerId ?? "";
    message.legionId = object.legionId ?? "";
    message.position = object.position ?? 0;
    message.joinTime = object.joinTime ?? "";
    message.todayContribution = object.todayContribution ?? 0;
    message.totalContribution = object.totalContribution ?? 0;
    message.quitTime = object.quitTime ?? "";
    return message;
  },
};

function createBaseLegionDetailInfo(): LegionDetailInfo {
  return { legionInfo: undefined, legionMemberInfos: [] };
}

export const LegionDetailInfo: MessageFns<LegionDetailInfo> = {
  encode(message: LegionDetailInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legionInfo !== undefined) {
      LegionInfo.encode(message.legionInfo, writer.uint32(10).fork()).join();
    }
    for (const v of message.legionMemberInfos) {
      LegionMemberInfo.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LegionDetailInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLegionDetailInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.legionInfo = LegionInfo.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.legionMemberInfos.push(LegionMemberInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LegionDetailInfo {
    return {
      legionInfo: isSet(object.legionInfo) ? LegionInfo.fromJSON(object.legionInfo) : undefined,
      legionMemberInfos: globalThis.Array.isArray(object?.legionMemberInfos)
        ? object.legionMemberInfos.map((e: any) => LegionMemberInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: LegionDetailInfo): unknown {
    const obj: any = {};
    if (message.legionInfo !== undefined) {
      obj.legionInfo = LegionInfo.toJSON(message.legionInfo);
    }
    if (message.legionMemberInfos?.length) {
      obj.legionMemberInfos = message.legionMemberInfos.map((e) => LegionMemberInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LegionDetailInfo>, I>>(base?: I): LegionDetailInfo {
    return LegionDetailInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LegionDetailInfo>, I>>(object: I): LegionDetailInfo {
    const message = createBaseLegionDetailInfo();
    message.legionInfo = (object.legionInfo !== undefined && object.legionInfo !== null)
      ? LegionInfo.fromPartial(object.legionInfo)
      : undefined;
    message.legionMemberInfos = object.legionMemberInfos?.map((e) => LegionMemberInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCityInfo(): CityInfo {
  return {
    cityId: 0,
    ownerLegionInfo: undefined,
    cityStatus: 0,
    garrisonCurrentCount: 0,
    lastAddGarrisonTime: "",
    declaringLegionInfo: undefined,
    statusChangeTime: "",
    isUnlock: false,
    battleInfo: [],
    battleRemainingTime: 0,
  };
}

export const CityInfo: MessageFns<CityInfo> = {
  encode(message: CityInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cityId !== 0) {
      writer.uint32(8).int32(message.cityId);
    }
    if (message.ownerLegionInfo !== undefined) {
      LegionBaseInfo.encode(message.ownerLegionInfo, writer.uint32(18).fork()).join();
    }
    if (message.cityStatus !== 0) {
      writer.uint32(24).int32(message.cityStatus);
    }
    if (message.garrisonCurrentCount !== 0) {
      writer.uint32(32).int32(message.garrisonCurrentCount);
    }
    if (message.lastAddGarrisonTime !== "") {
      writer.uint32(42).string(message.lastAddGarrisonTime);
    }
    if (message.declaringLegionInfo !== undefined) {
      LegionBaseInfo.encode(message.declaringLegionInfo, writer.uint32(50).fork()).join();
    }
    if (message.statusChangeTime !== "") {
      writer.uint32(58).string(message.statusChangeTime);
    }
    if (message.isUnlock !== false) {
      writer.uint32(64).bool(message.isUnlock);
    }
    for (const v of message.battleInfo) {
      BattleInfo.encode(v!, writer.uint32(74).fork()).join();
    }
    if (message.battleRemainingTime !== 0) {
      writer.uint32(80).int32(message.battleRemainingTime);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CityInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCityInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.cityId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ownerLegionInfo = LegionBaseInfo.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.cityStatus = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.garrisonCurrentCount = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.lastAddGarrisonTime = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.declaringLegionInfo = LegionBaseInfo.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.statusChangeTime = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.isUnlock = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.battleInfo.push(BattleInfo.decode(reader, reader.uint32()));
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.battleRemainingTime = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CityInfo {
    return {
      cityId: isSet(object.cityId) ? globalThis.Number(object.cityId) : 0,
      ownerLegionInfo: isSet(object.ownerLegionInfo) ? LegionBaseInfo.fromJSON(object.ownerLegionInfo) : undefined,
      cityStatus: isSet(object.cityStatus) ? globalThis.Number(object.cityStatus) : 0,
      garrisonCurrentCount: isSet(object.garrisonCurrentCount) ? globalThis.Number(object.garrisonCurrentCount) : 0,
      lastAddGarrisonTime: isSet(object.lastAddGarrisonTime) ? globalThis.String(object.lastAddGarrisonTime) : "",
      declaringLegionInfo: isSet(object.declaringLegionInfo)
        ? LegionBaseInfo.fromJSON(object.declaringLegionInfo)
        : undefined,
      statusChangeTime: isSet(object.statusChangeTime) ? globalThis.String(object.statusChangeTime) : "",
      isUnlock: isSet(object.isUnlock) ? globalThis.Boolean(object.isUnlock) : false,
      battleInfo: globalThis.Array.isArray(object?.battleInfo)
        ? object.battleInfo.map((e: any) => BattleInfo.fromJSON(e))
        : [],
      battleRemainingTime: isSet(object.battleRemainingTime) ? globalThis.Number(object.battleRemainingTime) : 0,
    };
  },

  toJSON(message: CityInfo): unknown {
    const obj: any = {};
    if (message.cityId !== 0) {
      obj.cityId = Math.round(message.cityId);
    }
    if (message.ownerLegionInfo !== undefined) {
      obj.ownerLegionInfo = LegionBaseInfo.toJSON(message.ownerLegionInfo);
    }
    if (message.cityStatus !== 0) {
      obj.cityStatus = Math.round(message.cityStatus);
    }
    if (message.garrisonCurrentCount !== 0) {
      obj.garrisonCurrentCount = Math.round(message.garrisonCurrentCount);
    }
    if (message.lastAddGarrisonTime !== "") {
      obj.lastAddGarrisonTime = message.lastAddGarrisonTime;
    }
    if (message.declaringLegionInfo !== undefined) {
      obj.declaringLegionInfo = LegionBaseInfo.toJSON(message.declaringLegionInfo);
    }
    if (message.statusChangeTime !== "") {
      obj.statusChangeTime = message.statusChangeTime;
    }
    if (message.isUnlock !== false) {
      obj.isUnlock = message.isUnlock;
    }
    if (message.battleInfo?.length) {
      obj.battleInfo = message.battleInfo.map((e) => BattleInfo.toJSON(e));
    }
    if (message.battleRemainingTime !== 0) {
      obj.battleRemainingTime = Math.round(message.battleRemainingTime);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CityInfo>, I>>(base?: I): CityInfo {
    return CityInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CityInfo>, I>>(object: I): CityInfo {
    const message = createBaseCityInfo();
    message.cityId = object.cityId ?? 0;
    message.ownerLegionInfo = (object.ownerLegionInfo !== undefined && object.ownerLegionInfo !== null)
      ? LegionBaseInfo.fromPartial(object.ownerLegionInfo)
      : undefined;
    message.cityStatus = object.cityStatus ?? 0;
    message.garrisonCurrentCount = object.garrisonCurrentCount ?? 0;
    message.lastAddGarrisonTime = object.lastAddGarrisonTime ?? "";
    message.declaringLegionInfo = (object.declaringLegionInfo !== undefined && object.declaringLegionInfo !== null)
      ? LegionBaseInfo.fromPartial(object.declaringLegionInfo)
      : undefined;
    message.statusChangeTime = object.statusChangeTime ?? "";
    message.isUnlock = object.isUnlock ?? false;
    message.battleInfo = object.battleInfo?.map((e) => BattleInfo.fromPartial(e)) || [];
    message.battleRemainingTime = object.battleRemainingTime ?? 0;
    return message;
  },
};

function createBaseBattleInfo(): BattleInfo {
  return { battleIndex: 0, attack: undefined, defend: undefined };
}

export const BattleInfo: MessageFns<BattleInfo> = {
  encode(message: BattleInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.battleIndex !== 0) {
      writer.uint32(8).int32(message.battleIndex);
    }
    if (message.attack !== undefined) {
      BattleUnit.encode(message.attack, writer.uint32(18).fork()).join();
    }
    if (message.defend !== undefined) {
      BattleUnit.encode(message.defend, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BattleInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBattleInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.battleIndex = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.attack = BattleUnit.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.defend = BattleUnit.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BattleInfo {
    return {
      battleIndex: isSet(object.battleIndex) ? globalThis.Number(object.battleIndex) : 0,
      attack: isSet(object.attack) ? BattleUnit.fromJSON(object.attack) : undefined,
      defend: isSet(object.defend) ? BattleUnit.fromJSON(object.defend) : undefined,
    };
  },

  toJSON(message: BattleInfo): unknown {
    const obj: any = {};
    if (message.battleIndex !== 0) {
      obj.battleIndex = Math.round(message.battleIndex);
    }
    if (message.attack !== undefined) {
      obj.attack = BattleUnit.toJSON(message.attack);
    }
    if (message.defend !== undefined) {
      obj.defend = BattleUnit.toJSON(message.defend);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BattleInfo>, I>>(base?: I): BattleInfo {
    return BattleInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BattleInfo>, I>>(object: I): BattleInfo {
    const message = createBaseBattleInfo();
    message.battleIndex = object.battleIndex ?? 0;
    message.attack = (object.attack !== undefined && object.attack !== null)
      ? BattleUnit.fromPartial(object.attack)
      : undefined;
    message.defend = (object.defend !== undefined && object.defend !== null)
      ? BattleUnit.fromPartial(object.defend)
      : undefined;
    return message;
  },
};

function createBaseHeroState(): HeroState {
  return { heroId: 0, maxHp: "", currentHp: "", debuffStacks: 0, garrisonType: 0 };
}

export const HeroState: MessageFns<HeroState> = {
  encode(message: HeroState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.heroId !== 0) {
      writer.uint32(8).int32(message.heroId);
    }
    if (message.maxHp !== "") {
      writer.uint32(18).string(message.maxHp);
    }
    if (message.currentHp !== "") {
      writer.uint32(26).string(message.currentHp);
    }
    if (message.debuffStacks !== 0) {
      writer.uint32(32).int32(message.debuffStacks);
    }
    if (message.garrisonType !== 0) {
      writer.uint32(40).int32(message.garrisonType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HeroState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeroState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.heroId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.maxHp = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.currentHp = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.debuffStacks = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.garrisonType = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HeroState {
    return {
      heroId: isSet(object.heroId) ? globalThis.Number(object.heroId) : 0,
      maxHp: isSet(object.maxHp) ? globalThis.String(object.maxHp) : "",
      currentHp: isSet(object.currentHp) ? globalThis.String(object.currentHp) : "",
      debuffStacks: isSet(object.debuffStacks) ? globalThis.Number(object.debuffStacks) : 0,
      garrisonType: isSet(object.garrisonType) ? globalThis.Number(object.garrisonType) : 0,
    };
  },

  toJSON(message: HeroState): unknown {
    const obj: any = {};
    if (message.heroId !== 0) {
      obj.heroId = Math.round(message.heroId);
    }
    if (message.maxHp !== "") {
      obj.maxHp = message.maxHp;
    }
    if (message.currentHp !== "") {
      obj.currentHp = message.currentHp;
    }
    if (message.debuffStacks !== 0) {
      obj.debuffStacks = Math.round(message.debuffStacks);
    }
    if (message.garrisonType !== 0) {
      obj.garrisonType = Math.round(message.garrisonType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HeroState>, I>>(base?: I): HeroState {
    return HeroState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HeroState>, I>>(object: I): HeroState {
    const message = createBaseHeroState();
    message.heroId = object.heroId ?? 0;
    message.maxHp = object.maxHp ?? "";
    message.currentHp = object.currentHp ?? "";
    message.debuffStacks = object.debuffStacks ?? 0;
    message.garrisonType = object.garrisonType ?? 0;
    return message;
  },
};

function createBaseBattleUnit(): BattleUnit {
  return {
    hero: [],
    playerId: "",
    playerName: "",
    legionId: "",
    legionName: "",
    totalPower: "",
    isGarrison: false,
    dispatchId: "",
  };
}

export const BattleUnit: MessageFns<BattleUnit> = {
  encode(message: BattleUnit, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.hero) {
      HeroState.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.playerId !== "") {
      writer.uint32(18).string(message.playerId);
    }
    if (message.playerName !== "") {
      writer.uint32(26).string(message.playerName);
    }
    if (message.legionId !== "") {
      writer.uint32(34).string(message.legionId);
    }
    if (message.legionName !== "") {
      writer.uint32(42).string(message.legionName);
    }
    if (message.totalPower !== "") {
      writer.uint32(50).string(message.totalPower);
    }
    if (message.isGarrison !== false) {
      writer.uint32(56).bool(message.isGarrison);
    }
    if (message.dispatchId !== "") {
      writer.uint32(66).string(message.dispatchId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BattleUnit {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBattleUnit();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.hero.push(HeroState.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.playerId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.playerName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.legionId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.legionName = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.totalPower = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.isGarrison = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.dispatchId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BattleUnit {
    return {
      hero: globalThis.Array.isArray(object?.hero) ? object.hero.map((e: any) => HeroState.fromJSON(e)) : [],
      playerId: isSet(object.playerId) ? globalThis.String(object.playerId) : "",
      playerName: isSet(object.playerName) ? globalThis.String(object.playerName) : "",
      legionId: isSet(object.legionId) ? globalThis.String(object.legionId) : "",
      legionName: isSet(object.legionName) ? globalThis.String(object.legionName) : "",
      totalPower: isSet(object.totalPower) ? globalThis.String(object.totalPower) : "",
      isGarrison: isSet(object.isGarrison) ? globalThis.Boolean(object.isGarrison) : false,
      dispatchId: isSet(object.dispatchId) ? globalThis.String(object.dispatchId) : "",
    };
  },

  toJSON(message: BattleUnit): unknown {
    const obj: any = {};
    if (message.hero?.length) {
      obj.hero = message.hero.map((e) => HeroState.toJSON(e));
    }
    if (message.playerId !== "") {
      obj.playerId = message.playerId;
    }
    if (message.playerName !== "") {
      obj.playerName = message.playerName;
    }
    if (message.legionId !== "") {
      obj.legionId = message.legionId;
    }
    if (message.legionName !== "") {
      obj.legionName = message.legionName;
    }
    if (message.totalPower !== "") {
      obj.totalPower = message.totalPower;
    }
    if (message.isGarrison !== false) {
      obj.isGarrison = message.isGarrison;
    }
    if (message.dispatchId !== "") {
      obj.dispatchId = message.dispatchId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BattleUnit>, I>>(base?: I): BattleUnit {
    return BattleUnit.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BattleUnit>, I>>(object: I): BattleUnit {
    const message = createBaseBattleUnit();
    message.hero = object.hero?.map((e) => HeroState.fromPartial(e)) || [];
    message.playerId = object.playerId ?? "";
    message.playerName = object.playerName ?? "";
    message.legionId = object.legionId ?? "";
    message.legionName = object.legionName ?? "";
    message.totalPower = object.totalPower ?? "";
    message.isGarrison = object.isGarrison ?? false;
    message.dispatchId = object.dispatchId ?? "";
    return message;
  },
};

function createBaseCityBattleDetail(): CityBattleDetail {
  return { battleInfo: [], attackQueue: [], defendQueue: [], garrisonQueue: [], battleRemainingTime: 0, cityId: 0 };
}

export const CityBattleDetail: MessageFns<CityBattleDetail> = {
  encode(message: CityBattleDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.battleInfo) {
      BattleInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.attackQueue) {
      BattleUnit.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.defendQueue) {
      BattleUnit.encode(v!, writer.uint32(26).fork()).join();
    }
    for (const v of message.garrisonQueue) {
      BattleUnit.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.battleRemainingTime !== 0) {
      writer.uint32(40).int32(message.battleRemainingTime);
    }
    if (message.cityId !== 0) {
      writer.uint32(48).int32(message.cityId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CityBattleDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCityBattleDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.battleInfo.push(BattleInfo.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.attackQueue.push(BattleUnit.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.defendQueue.push(BattleUnit.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.garrisonQueue.push(BattleUnit.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.battleRemainingTime = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.cityId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CityBattleDetail {
    return {
      battleInfo: globalThis.Array.isArray(object?.battleInfo)
        ? object.battleInfo.map((e: any) => BattleInfo.fromJSON(e))
        : [],
      attackQueue: globalThis.Array.isArray(object?.attackQueue)
        ? object.attackQueue.map((e: any) => BattleUnit.fromJSON(e))
        : [],
      defendQueue: globalThis.Array.isArray(object?.defendQueue)
        ? object.defendQueue.map((e: any) => BattleUnit.fromJSON(e))
        : [],
      garrisonQueue: globalThis.Array.isArray(object?.garrisonQueue)
        ? object.garrisonQueue.map((e: any) => BattleUnit.fromJSON(e))
        : [],
      battleRemainingTime: isSet(object.battleRemainingTime) ? globalThis.Number(object.battleRemainingTime) : 0,
      cityId: isSet(object.cityId) ? globalThis.Number(object.cityId) : 0,
    };
  },

  toJSON(message: CityBattleDetail): unknown {
    const obj: any = {};
    if (message.battleInfo?.length) {
      obj.battleInfo = message.battleInfo.map((e) => BattleInfo.toJSON(e));
    }
    if (message.attackQueue?.length) {
      obj.attackQueue = message.attackQueue.map((e) => BattleUnit.toJSON(e));
    }
    if (message.defendQueue?.length) {
      obj.defendQueue = message.defendQueue.map((e) => BattleUnit.toJSON(e));
    }
    if (message.garrisonQueue?.length) {
      obj.garrisonQueue = message.garrisonQueue.map((e) => BattleUnit.toJSON(e));
    }
    if (message.battleRemainingTime !== 0) {
      obj.battleRemainingTime = Math.round(message.battleRemainingTime);
    }
    if (message.cityId !== 0) {
      obj.cityId = Math.round(message.cityId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CityBattleDetail>, I>>(base?: I): CityBattleDetail {
    return CityBattleDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CityBattleDetail>, I>>(object: I): CityBattleDetail {
    const message = createBaseCityBattleDetail();
    message.battleInfo = object.battleInfo?.map((e) => BattleInfo.fromPartial(e)) || [];
    message.attackQueue = object.attackQueue?.map((e) => BattleUnit.fromPartial(e)) || [];
    message.defendQueue = object.defendQueue?.map((e) => BattleUnit.fromPartial(e)) || [];
    message.garrisonQueue = object.garrisonQueue?.map((e) => BattleUnit.fromPartial(e)) || [];
    message.battleRemainingTime = object.battleRemainingTime ?? 0;
    message.cityId = object.cityId ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
